// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: autopilot.proto
// Protobuf C++ Version: 5.28.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_autopilot_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_autopilot_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_autopilot_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_autopilot_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_autopilot_2eproto;
namespace autopilotrpc {
class ModifyStatusRequest;
struct ModifyStatusRequestDefaultTypeInternal;
extern ModifyStatusRequestDefaultTypeInternal _ModifyStatusRequest_default_instance_;
class ModifyStatusResponse;
struct ModifyStatusResponseDefaultTypeInternal;
extern ModifyStatusResponseDefaultTypeInternal _ModifyStatusResponse_default_instance_;
class QueryScoresRequest;
struct QueryScoresRequestDefaultTypeInternal;
extern QueryScoresRequestDefaultTypeInternal _QueryScoresRequest_default_instance_;
class QueryScoresResponse;
struct QueryScoresResponseDefaultTypeInternal;
extern QueryScoresResponseDefaultTypeInternal _QueryScoresResponse_default_instance_;
class QueryScoresResponse_HeuristicResult;
struct QueryScoresResponse_HeuristicResultDefaultTypeInternal;
extern QueryScoresResponse_HeuristicResultDefaultTypeInternal _QueryScoresResponse_HeuristicResult_default_instance_;
class QueryScoresResponse_HeuristicResult_ScoresEntry_DoNotUse;
struct QueryScoresResponse_HeuristicResult_ScoresEntry_DoNotUseDefaultTypeInternal;
extern QueryScoresResponse_HeuristicResult_ScoresEntry_DoNotUseDefaultTypeInternal _QueryScoresResponse_HeuristicResult_ScoresEntry_DoNotUse_default_instance_;
class SetScoresRequest;
struct SetScoresRequestDefaultTypeInternal;
extern SetScoresRequestDefaultTypeInternal _SetScoresRequest_default_instance_;
class SetScoresRequest_ScoresEntry_DoNotUse;
struct SetScoresRequest_ScoresEntry_DoNotUseDefaultTypeInternal;
extern SetScoresRequest_ScoresEntry_DoNotUseDefaultTypeInternal _SetScoresRequest_ScoresEntry_DoNotUse_default_instance_;
class SetScoresResponse;
struct SetScoresResponseDefaultTypeInternal;
extern SetScoresResponseDefaultTypeInternal _SetScoresResponse_default_instance_;
class StatusRequest;
struct StatusRequestDefaultTypeInternal;
extern StatusRequestDefaultTypeInternal _StatusRequest_default_instance_;
class StatusResponse;
struct StatusResponseDefaultTypeInternal;
extern StatusResponseDefaultTypeInternal _StatusResponse_default_instance_;
}  // namespace autopilotrpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace autopilotrpc {

// ===================================================================


// -------------------------------------------------------------------

class StatusResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:autopilotrpc.StatusResponse) */ {
 public:
  inline StatusResponse() : StatusResponse(nullptr) {}
  ~StatusResponse() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StatusResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline StatusResponse(const StatusResponse& from) : StatusResponse(nullptr, from) {}
  inline StatusResponse(StatusResponse&& from) noexcept
      : StatusResponse(nullptr, std::move(from)) {}
  inline StatusResponse& operator=(const StatusResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline StatusResponse& operator=(StatusResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StatusResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const StatusResponse* internal_default_instance() {
    return reinterpret_cast<const StatusResponse*>(
        &_StatusResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(StatusResponse& a, StatusResponse& b) { a.Swap(&b); }
  inline void Swap(StatusResponse* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StatusResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StatusResponse* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<StatusResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StatusResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StatusResponse& from) { StatusResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(StatusResponse* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "autopilotrpc.StatusResponse"; }

 protected:
  explicit StatusResponse(::google::protobuf::Arena* arena);
  StatusResponse(::google::protobuf::Arena* arena, const StatusResponse& from);
  StatusResponse(::google::protobuf::Arena* arena, StatusResponse&& from) noexcept
      : StatusResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kActiveFieldNumber = 1,
  };
  // bool active = 1;
  void clear_active() ;
  bool active() const;
  void set_active(bool value);

  private:
  bool _internal_active() const;
  void _internal_set_active(bool value);

  public:
  // @@protoc_insertion_point(class_scope:autopilotrpc.StatusResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_StatusResponse_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const StatusResponse& from_msg);
    bool active_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_autopilot_2eproto;
};
// -------------------------------------------------------------------

class StatusRequest final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:autopilotrpc.StatusRequest) */ {
 public:
  inline StatusRequest() : StatusRequest(nullptr) {}
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StatusRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline StatusRequest(const StatusRequest& from) : StatusRequest(nullptr, from) {}
  inline StatusRequest(StatusRequest&& from) noexcept
      : StatusRequest(nullptr, std::move(from)) {}
  inline StatusRequest& operator=(const StatusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StatusRequest& operator=(StatusRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StatusRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StatusRequest* internal_default_instance() {
    return reinterpret_cast<const StatusRequest*>(
        &_StatusRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(StatusRequest& a, StatusRequest& b) { a.Swap(&b); }
  inline void Swap(StatusRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StatusRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StatusRequest* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<StatusRequest>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const StatusRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const StatusRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "autopilotrpc.StatusRequest"; }

 protected:
  explicit StatusRequest(::google::protobuf::Arena* arena);
  StatusRequest(::google::protobuf::Arena* arena, const StatusRequest& from);
  StatusRequest(::google::protobuf::Arena* arena, StatusRequest&& from) noexcept
      : StatusRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ZeroFieldsBase::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::internal::ZeroFieldsBase::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:autopilotrpc.StatusRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_StatusRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const StatusRequest& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_autopilot_2eproto;
};
// -------------------------------------------------------------------

class SetScoresResponse final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:autopilotrpc.SetScoresResponse) */ {
 public:
  inline SetScoresResponse() : SetScoresResponse(nullptr) {}
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SetScoresResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline SetScoresResponse(const SetScoresResponse& from) : SetScoresResponse(nullptr, from) {}
  inline SetScoresResponse(SetScoresResponse&& from) noexcept
      : SetScoresResponse(nullptr, std::move(from)) {}
  inline SetScoresResponse& operator=(const SetScoresResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetScoresResponse& operator=(SetScoresResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetScoresResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SetScoresResponse* internal_default_instance() {
    return reinterpret_cast<const SetScoresResponse*>(
        &_SetScoresResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 10;
  friend void swap(SetScoresResponse& a, SetScoresResponse& b) { a.Swap(&b); }
  inline void Swap(SetScoresResponse* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetScoresResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetScoresResponse* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<SetScoresResponse>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const SetScoresResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const SetScoresResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "autopilotrpc.SetScoresResponse"; }

 protected:
  explicit SetScoresResponse(::google::protobuf::Arena* arena);
  SetScoresResponse(::google::protobuf::Arena* arena, const SetScoresResponse& from);
  SetScoresResponse(::google::protobuf::Arena* arena, SetScoresResponse&& from) noexcept
      : SetScoresResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ZeroFieldsBase::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::internal::ZeroFieldsBase::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:autopilotrpc.SetScoresResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_SetScoresResponse_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SetScoresResponse& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_autopilot_2eproto;
};
// -------------------------------------------------------------------

class SetScoresRequest_ScoresEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          SetScoresRequest_ScoresEntry_DoNotUse, std::string, double,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      SetScoresRequest_ScoresEntry_DoNotUse, std::string, double,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>;
  SetScoresRequest_ScoresEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SetScoresRequest_ScoresEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit SetScoresRequest_ScoresEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const SetScoresRequest_ScoresEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const SetScoresRequest_ScoresEntry_DoNotUse*>(
        &_SetScoresRequest_ScoresEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      53, 2>
      _table_;

  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;
  friend struct ::TableStruct_autopilot_2eproto;
};
// -------------------------------------------------------------------

class QueryScoresResponse_HeuristicResult_ScoresEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          QueryScoresResponse_HeuristicResult_ScoresEntry_DoNotUse, std::string, double,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      QueryScoresResponse_HeuristicResult_ScoresEntry_DoNotUse, std::string, double,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>;
  QueryScoresResponse_HeuristicResult_ScoresEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR QueryScoresResponse_HeuristicResult_ScoresEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit QueryScoresResponse_HeuristicResult_ScoresEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const QueryScoresResponse_HeuristicResult_ScoresEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const QueryScoresResponse_HeuristicResult_ScoresEntry_DoNotUse*>(
        &_QueryScoresResponse_HeuristicResult_ScoresEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      72, 2>
      _table_;

  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;
  friend struct ::TableStruct_autopilot_2eproto;
};
// -------------------------------------------------------------------

class QueryScoresRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:autopilotrpc.QueryScoresRequest) */ {
 public:
  inline QueryScoresRequest() : QueryScoresRequest(nullptr) {}
  ~QueryScoresRequest() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR QueryScoresRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline QueryScoresRequest(const QueryScoresRequest& from) : QueryScoresRequest(nullptr, from) {}
  inline QueryScoresRequest(QueryScoresRequest&& from) noexcept
      : QueryScoresRequest(nullptr, std::move(from)) {}
  inline QueryScoresRequest& operator=(const QueryScoresRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline QueryScoresRequest& operator=(QueryScoresRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QueryScoresRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const QueryScoresRequest* internal_default_instance() {
    return reinterpret_cast<const QueryScoresRequest*>(
        &_QueryScoresRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(QueryScoresRequest& a, QueryScoresRequest& b) { a.Swap(&b); }
  inline void Swap(QueryScoresRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QueryScoresRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QueryScoresRequest* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<QueryScoresRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const QueryScoresRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const QueryScoresRequest& from) { QueryScoresRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(QueryScoresRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "autopilotrpc.QueryScoresRequest"; }

 protected:
  explicit QueryScoresRequest(::google::protobuf::Arena* arena);
  QueryScoresRequest(::google::protobuf::Arena* arena, const QueryScoresRequest& from);
  QueryScoresRequest(::google::protobuf::Arena* arena, QueryScoresRequest&& from) noexcept
      : QueryScoresRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPubkeysFieldNumber = 1,
    kIgnoreLocalStateFieldNumber = 2,
  };
  // repeated string pubkeys = 1;
  int pubkeys_size() const;
  private:
  int _internal_pubkeys_size() const;

  public:
  void clear_pubkeys() ;
  const std::string& pubkeys(int index) const;
  std::string* mutable_pubkeys(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pubkeys(int index, Arg_&& value, Args_... args);
  std::string* add_pubkeys();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_pubkeys(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& pubkeys() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_pubkeys();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_pubkeys() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_pubkeys();

  public:
  // bool ignore_local_state = 2;
  void clear_ignore_local_state() ;
  bool ignore_local_state() const;
  void set_ignore_local_state(bool value);

  private:
  bool _internal_ignore_local_state() const;
  void _internal_set_ignore_local_state(bool value);

  public:
  // @@protoc_insertion_point(class_scope:autopilotrpc.QueryScoresRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      47, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_QueryScoresRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const QueryScoresRequest& from_msg);
    ::google::protobuf::RepeatedPtrField<std::string> pubkeys_;
    bool ignore_local_state_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_autopilot_2eproto;
};
// -------------------------------------------------------------------

class ModifyStatusResponse final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:autopilotrpc.ModifyStatusResponse) */ {
 public:
  inline ModifyStatusResponse() : ModifyStatusResponse(nullptr) {}
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ModifyStatusResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline ModifyStatusResponse(const ModifyStatusResponse& from) : ModifyStatusResponse(nullptr, from) {}
  inline ModifyStatusResponse(ModifyStatusResponse&& from) noexcept
      : ModifyStatusResponse(nullptr, std::move(from)) {}
  inline ModifyStatusResponse& operator=(const ModifyStatusResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModifyStatusResponse& operator=(ModifyStatusResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ModifyStatusResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ModifyStatusResponse* internal_default_instance() {
    return reinterpret_cast<const ModifyStatusResponse*>(
        &_ModifyStatusResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(ModifyStatusResponse& a, ModifyStatusResponse& b) { a.Swap(&b); }
  inline void Swap(ModifyStatusResponse* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModifyStatusResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ModifyStatusResponse* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<ModifyStatusResponse>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const ModifyStatusResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const ModifyStatusResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "autopilotrpc.ModifyStatusResponse"; }

 protected:
  explicit ModifyStatusResponse(::google::protobuf::Arena* arena);
  ModifyStatusResponse(::google::protobuf::Arena* arena, const ModifyStatusResponse& from);
  ModifyStatusResponse(::google::protobuf::Arena* arena, ModifyStatusResponse&& from) noexcept
      : ModifyStatusResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ZeroFieldsBase::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::internal::ZeroFieldsBase::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:autopilotrpc.ModifyStatusResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ModifyStatusResponse_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ModifyStatusResponse& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_autopilot_2eproto;
};
// -------------------------------------------------------------------

class ModifyStatusRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:autopilotrpc.ModifyStatusRequest) */ {
 public:
  inline ModifyStatusRequest() : ModifyStatusRequest(nullptr) {}
  ~ModifyStatusRequest() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ModifyStatusRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline ModifyStatusRequest(const ModifyStatusRequest& from) : ModifyStatusRequest(nullptr, from) {}
  inline ModifyStatusRequest(ModifyStatusRequest&& from) noexcept
      : ModifyStatusRequest(nullptr, std::move(from)) {}
  inline ModifyStatusRequest& operator=(const ModifyStatusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModifyStatusRequest& operator=(ModifyStatusRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ModifyStatusRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ModifyStatusRequest* internal_default_instance() {
    return reinterpret_cast<const ModifyStatusRequest*>(
        &_ModifyStatusRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ModifyStatusRequest& a, ModifyStatusRequest& b) { a.Swap(&b); }
  inline void Swap(ModifyStatusRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModifyStatusRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ModifyStatusRequest* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<ModifyStatusRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ModifyStatusRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ModifyStatusRequest& from) { ModifyStatusRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ModifyStatusRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "autopilotrpc.ModifyStatusRequest"; }

 protected:
  explicit ModifyStatusRequest(::google::protobuf::Arena* arena);
  ModifyStatusRequest(::google::protobuf::Arena* arena, const ModifyStatusRequest& from);
  ModifyStatusRequest(::google::protobuf::Arena* arena, ModifyStatusRequest&& from) noexcept
      : ModifyStatusRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEnableFieldNumber = 1,
  };
  // bool enable = 1;
  void clear_enable() ;
  bool enable() const;
  void set_enable(bool value);

  private:
  bool _internal_enable() const;
  void _internal_set_enable(bool value);

  public:
  // @@protoc_insertion_point(class_scope:autopilotrpc.ModifyStatusRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ModifyStatusRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ModifyStatusRequest& from_msg);
    bool enable_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_autopilot_2eproto;
};
// -------------------------------------------------------------------

class SetScoresRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:autopilotrpc.SetScoresRequest) */ {
 public:
  inline SetScoresRequest() : SetScoresRequest(nullptr) {}
  ~SetScoresRequest() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SetScoresRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline SetScoresRequest(const SetScoresRequest& from) : SetScoresRequest(nullptr, from) {}
  inline SetScoresRequest(SetScoresRequest&& from) noexcept
      : SetScoresRequest(nullptr, std::move(from)) {}
  inline SetScoresRequest& operator=(const SetScoresRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetScoresRequest& operator=(SetScoresRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetScoresRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SetScoresRequest* internal_default_instance() {
    return reinterpret_cast<const SetScoresRequest*>(
        &_SetScoresRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 9;
  friend void swap(SetScoresRequest& a, SetScoresRequest& b) { a.Swap(&b); }
  inline void Swap(SetScoresRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetScoresRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetScoresRequest* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<SetScoresRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SetScoresRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SetScoresRequest& from) { SetScoresRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(SetScoresRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "autopilotrpc.SetScoresRequest"; }

 protected:
  explicit SetScoresRequest(::google::protobuf::Arena* arena);
  SetScoresRequest(::google::protobuf::Arena* arena, const SetScoresRequest& from);
  SetScoresRequest(::google::protobuf::Arena* arena, SetScoresRequest&& from) noexcept
      : SetScoresRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kScoresFieldNumber = 2,
    kHeuristicFieldNumber = 1,
  };
  // map<string, double> scores = 2;
  int scores_size() const;
  private:
  int _internal_scores_size() const;

  public:
  void clear_scores() ;
  const ::google::protobuf::Map<std::string, double>& scores() const;
  ::google::protobuf::Map<std::string, double>* mutable_scores();

  private:
  const ::google::protobuf::Map<std::string, double>& _internal_scores() const;
  ::google::protobuf::Map<std::string, double>* _internal_mutable_scores();

  public:
  // string heuristic = 1;
  void clear_heuristic() ;
  const std::string& heuristic() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_heuristic(Arg_&& arg, Args_... args);
  std::string* mutable_heuristic();
  PROTOBUF_NODISCARD std::string* release_heuristic();
  void set_allocated_heuristic(std::string* value);

  private:
  const std::string& _internal_heuristic() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_heuristic(
      const std::string& value);
  std::string* _internal_mutable_heuristic();

  public:
  // @@protoc_insertion_point(class_scope:autopilotrpc.SetScoresRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 2, 1,
      53, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_SetScoresRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SetScoresRequest& from_msg);
    ::google::protobuf::internal::MapField<SetScoresRequest_ScoresEntry_DoNotUse, std::string, double,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>
        scores_;
    ::google::protobuf::internal::ArenaStringPtr heuristic_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_autopilot_2eproto;
};
// -------------------------------------------------------------------

class QueryScoresResponse_HeuristicResult final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:autopilotrpc.QueryScoresResponse.HeuristicResult) */ {
 public:
  inline QueryScoresResponse_HeuristicResult() : QueryScoresResponse_HeuristicResult(nullptr) {}
  ~QueryScoresResponse_HeuristicResult() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR QueryScoresResponse_HeuristicResult(
      ::google::protobuf::internal::ConstantInitialized);

  inline QueryScoresResponse_HeuristicResult(const QueryScoresResponse_HeuristicResult& from) : QueryScoresResponse_HeuristicResult(nullptr, from) {}
  inline QueryScoresResponse_HeuristicResult(QueryScoresResponse_HeuristicResult&& from) noexcept
      : QueryScoresResponse_HeuristicResult(nullptr, std::move(from)) {}
  inline QueryScoresResponse_HeuristicResult& operator=(const QueryScoresResponse_HeuristicResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline QueryScoresResponse_HeuristicResult& operator=(QueryScoresResponse_HeuristicResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QueryScoresResponse_HeuristicResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const QueryScoresResponse_HeuristicResult* internal_default_instance() {
    return reinterpret_cast<const QueryScoresResponse_HeuristicResult*>(
        &_QueryScoresResponse_HeuristicResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(QueryScoresResponse_HeuristicResult& a, QueryScoresResponse_HeuristicResult& b) { a.Swap(&b); }
  inline void Swap(QueryScoresResponse_HeuristicResult* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QueryScoresResponse_HeuristicResult* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QueryScoresResponse_HeuristicResult* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<QueryScoresResponse_HeuristicResult>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const QueryScoresResponse_HeuristicResult& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const QueryScoresResponse_HeuristicResult& from) { QueryScoresResponse_HeuristicResult::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(QueryScoresResponse_HeuristicResult* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "autopilotrpc.QueryScoresResponse.HeuristicResult"; }

 protected:
  explicit QueryScoresResponse_HeuristicResult(::google::protobuf::Arena* arena);
  QueryScoresResponse_HeuristicResult(::google::protobuf::Arena* arena, const QueryScoresResponse_HeuristicResult& from);
  QueryScoresResponse_HeuristicResult(::google::protobuf::Arena* arena, QueryScoresResponse_HeuristicResult&& from) noexcept
      : QueryScoresResponse_HeuristicResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kScoresFieldNumber = 2,
    kHeuristicFieldNumber = 1,
  };
  // map<string, double> scores = 2;
  int scores_size() const;
  private:
  int _internal_scores_size() const;

  public:
  void clear_scores() ;
  const ::google::protobuf::Map<std::string, double>& scores() const;
  ::google::protobuf::Map<std::string, double>* mutable_scores();

  private:
  const ::google::protobuf::Map<std::string, double>& _internal_scores() const;
  ::google::protobuf::Map<std::string, double>* _internal_mutable_scores();

  public:
  // string heuristic = 1;
  void clear_heuristic() ;
  const std::string& heuristic() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_heuristic(Arg_&& arg, Args_... args);
  std::string* mutable_heuristic();
  PROTOBUF_NODISCARD std::string* release_heuristic();
  void set_allocated_heuristic(std::string* value);

  private:
  const std::string& _internal_heuristic() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_heuristic(
      const std::string& value);
  std::string* _internal_mutable_heuristic();

  public:
  // @@protoc_insertion_point(class_scope:autopilotrpc.QueryScoresResponse.HeuristicResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 2, 1,
      72, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_QueryScoresResponse_HeuristicResult_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const QueryScoresResponse_HeuristicResult& from_msg);
    ::google::protobuf::internal::MapField<QueryScoresResponse_HeuristicResult_ScoresEntry_DoNotUse, std::string, double,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>
        scores_;
    ::google::protobuf::internal::ArenaStringPtr heuristic_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_autopilot_2eproto;
};
// -------------------------------------------------------------------

class QueryScoresResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:autopilotrpc.QueryScoresResponse) */ {
 public:
  inline QueryScoresResponse() : QueryScoresResponse(nullptr) {}
  ~QueryScoresResponse() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR QueryScoresResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline QueryScoresResponse(const QueryScoresResponse& from) : QueryScoresResponse(nullptr, from) {}
  inline QueryScoresResponse(QueryScoresResponse&& from) noexcept
      : QueryScoresResponse(nullptr, std::move(from)) {}
  inline QueryScoresResponse& operator=(const QueryScoresResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline QueryScoresResponse& operator=(QueryScoresResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QueryScoresResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const QueryScoresResponse* internal_default_instance() {
    return reinterpret_cast<const QueryScoresResponse*>(
        &_QueryScoresResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 7;
  friend void swap(QueryScoresResponse& a, QueryScoresResponse& b) { a.Swap(&b); }
  inline void Swap(QueryScoresResponse* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QueryScoresResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QueryScoresResponse* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<QueryScoresResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const QueryScoresResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const QueryScoresResponse& from) { QueryScoresResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(QueryScoresResponse* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "autopilotrpc.QueryScoresResponse"; }

 protected:
  explicit QueryScoresResponse(::google::protobuf::Arena* arena);
  QueryScoresResponse(::google::protobuf::Arena* arena, const QueryScoresResponse& from);
  QueryScoresResponse(::google::protobuf::Arena* arena, QueryScoresResponse&& from) noexcept
      : QueryScoresResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using HeuristicResult = QueryScoresResponse_HeuristicResult;

  // accessors -------------------------------------------------------
  enum : int {
    kResultsFieldNumber = 1,
  };
  // repeated .autopilotrpc.QueryScoresResponse.HeuristicResult results = 1;
  int results_size() const;
  private:
  int _internal_results_size() const;

  public:
  void clear_results() ;
  ::autopilotrpc::QueryScoresResponse_HeuristicResult* mutable_results(int index);
  ::google::protobuf::RepeatedPtrField<::autopilotrpc::QueryScoresResponse_HeuristicResult>* mutable_results();

  private:
  const ::google::protobuf::RepeatedPtrField<::autopilotrpc::QueryScoresResponse_HeuristicResult>& _internal_results() const;
  ::google::protobuf::RepeatedPtrField<::autopilotrpc::QueryScoresResponse_HeuristicResult>* _internal_mutable_results();
  public:
  const ::autopilotrpc::QueryScoresResponse_HeuristicResult& results(int index) const;
  ::autopilotrpc::QueryScoresResponse_HeuristicResult* add_results();
  const ::google::protobuf::RepeatedPtrField<::autopilotrpc::QueryScoresResponse_HeuristicResult>& results() const;
  // @@protoc_insertion_point(class_scope:autopilotrpc.QueryScoresResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_QueryScoresResponse_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const QueryScoresResponse& from_msg);
    ::google::protobuf::RepeatedPtrField< ::autopilotrpc::QueryScoresResponse_HeuristicResult > results_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_autopilot_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// StatusRequest

// -------------------------------------------------------------------

// StatusResponse

// bool active = 1;
inline void StatusResponse::clear_active() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.active_ = false;
}
inline bool StatusResponse::active() const {
  // @@protoc_insertion_point(field_get:autopilotrpc.StatusResponse.active)
  return _internal_active();
}
inline void StatusResponse::set_active(bool value) {
  _internal_set_active(value);
  // @@protoc_insertion_point(field_set:autopilotrpc.StatusResponse.active)
}
inline bool StatusResponse::_internal_active() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.active_;
}
inline void StatusResponse::_internal_set_active(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.active_ = value;
}

// -------------------------------------------------------------------

// ModifyStatusRequest

// bool enable = 1;
inline void ModifyStatusRequest::clear_enable() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enable_ = false;
}
inline bool ModifyStatusRequest::enable() const {
  // @@protoc_insertion_point(field_get:autopilotrpc.ModifyStatusRequest.enable)
  return _internal_enable();
}
inline void ModifyStatusRequest::set_enable(bool value) {
  _internal_set_enable(value);
  // @@protoc_insertion_point(field_set:autopilotrpc.ModifyStatusRequest.enable)
}
inline bool ModifyStatusRequest::_internal_enable() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enable_;
}
inline void ModifyStatusRequest::_internal_set_enable(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enable_ = value;
}

// -------------------------------------------------------------------

// ModifyStatusResponse

// -------------------------------------------------------------------

// QueryScoresRequest

// repeated string pubkeys = 1;
inline int QueryScoresRequest::_internal_pubkeys_size() const {
  return _internal_pubkeys().size();
}
inline int QueryScoresRequest::pubkeys_size() const {
  return _internal_pubkeys_size();
}
inline void QueryScoresRequest::clear_pubkeys() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pubkeys_.Clear();
}
inline std::string* QueryScoresRequest::add_pubkeys() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_pubkeys()->Add();
  // @@protoc_insertion_point(field_add_mutable:autopilotrpc.QueryScoresRequest.pubkeys)
  return _s;
}
inline const std::string& QueryScoresRequest::pubkeys(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:autopilotrpc.QueryScoresRequest.pubkeys)
  return _internal_pubkeys().Get(index);
}
inline std::string* QueryScoresRequest::mutable_pubkeys(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:autopilotrpc.QueryScoresRequest.pubkeys)
  return _internal_mutable_pubkeys()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void QueryScoresRequest::set_pubkeys(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_pubkeys()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:autopilotrpc.QueryScoresRequest.pubkeys)
}
template <typename Arg_, typename... Args_>
inline void QueryScoresRequest::add_pubkeys(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_pubkeys(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:autopilotrpc.QueryScoresRequest.pubkeys)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
QueryScoresRequest::pubkeys() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:autopilotrpc.QueryScoresRequest.pubkeys)
  return _internal_pubkeys();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
QueryScoresRequest::mutable_pubkeys() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:autopilotrpc.QueryScoresRequest.pubkeys)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pubkeys();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
QueryScoresRequest::_internal_pubkeys() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pubkeys_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
QueryScoresRequest::_internal_mutable_pubkeys() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pubkeys_;
}

// bool ignore_local_state = 2;
inline void QueryScoresRequest::clear_ignore_local_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ignore_local_state_ = false;
}
inline bool QueryScoresRequest::ignore_local_state() const {
  // @@protoc_insertion_point(field_get:autopilotrpc.QueryScoresRequest.ignore_local_state)
  return _internal_ignore_local_state();
}
inline void QueryScoresRequest::set_ignore_local_state(bool value) {
  _internal_set_ignore_local_state(value);
  // @@protoc_insertion_point(field_set:autopilotrpc.QueryScoresRequest.ignore_local_state)
}
inline bool QueryScoresRequest::_internal_ignore_local_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ignore_local_state_;
}
inline void QueryScoresRequest::_internal_set_ignore_local_state(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ignore_local_state_ = value;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// QueryScoresResponse_HeuristicResult

// string heuristic = 1;
inline void QueryScoresResponse_HeuristicResult::clear_heuristic() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heuristic_.ClearToEmpty();
}
inline const std::string& QueryScoresResponse_HeuristicResult::heuristic() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:autopilotrpc.QueryScoresResponse.HeuristicResult.heuristic)
  return _internal_heuristic();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void QueryScoresResponse_HeuristicResult::set_heuristic(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heuristic_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:autopilotrpc.QueryScoresResponse.HeuristicResult.heuristic)
}
inline std::string* QueryScoresResponse_HeuristicResult::mutable_heuristic() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_heuristic();
  // @@protoc_insertion_point(field_mutable:autopilotrpc.QueryScoresResponse.HeuristicResult.heuristic)
  return _s;
}
inline const std::string& QueryScoresResponse_HeuristicResult::_internal_heuristic() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heuristic_.Get();
}
inline void QueryScoresResponse_HeuristicResult::_internal_set_heuristic(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heuristic_.Set(value, GetArena());
}
inline std::string* QueryScoresResponse_HeuristicResult::_internal_mutable_heuristic() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.heuristic_.Mutable( GetArena());
}
inline std::string* QueryScoresResponse_HeuristicResult::release_heuristic() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:autopilotrpc.QueryScoresResponse.HeuristicResult.heuristic)
  return _impl_.heuristic_.Release();
}
inline void QueryScoresResponse_HeuristicResult::set_allocated_heuristic(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heuristic_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.heuristic_.IsDefault()) {
          _impl_.heuristic_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:autopilotrpc.QueryScoresResponse.HeuristicResult.heuristic)
}

// map<string, double> scores = 2;
inline int QueryScoresResponse_HeuristicResult::_internal_scores_size() const {
  return _internal_scores().size();
}
inline int QueryScoresResponse_HeuristicResult::scores_size() const {
  return _internal_scores_size();
}
inline void QueryScoresResponse_HeuristicResult::clear_scores() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scores_.Clear();
}
inline const ::google::protobuf::Map<std::string, double>& QueryScoresResponse_HeuristicResult::_internal_scores() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scores_.GetMap();
}
inline const ::google::protobuf::Map<std::string, double>& QueryScoresResponse_HeuristicResult::scores() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:autopilotrpc.QueryScoresResponse.HeuristicResult.scores)
  return _internal_scores();
}
inline ::google::protobuf::Map<std::string, double>* QueryScoresResponse_HeuristicResult::_internal_mutable_scores() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.scores_.MutableMap();
}
inline ::google::protobuf::Map<std::string, double>* QueryScoresResponse_HeuristicResult::mutable_scores() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:autopilotrpc.QueryScoresResponse.HeuristicResult.scores)
  return _internal_mutable_scores();
}

// -------------------------------------------------------------------

// QueryScoresResponse

// repeated .autopilotrpc.QueryScoresResponse.HeuristicResult results = 1;
inline int QueryScoresResponse::_internal_results_size() const {
  return _internal_results().size();
}
inline int QueryScoresResponse::results_size() const {
  return _internal_results_size();
}
inline void QueryScoresResponse::clear_results() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.results_.Clear();
}
inline ::autopilotrpc::QueryScoresResponse_HeuristicResult* QueryScoresResponse::mutable_results(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:autopilotrpc.QueryScoresResponse.results)
  return _internal_mutable_results()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::autopilotrpc::QueryScoresResponse_HeuristicResult>* QueryScoresResponse::mutable_results()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:autopilotrpc.QueryScoresResponse.results)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_results();
}
inline const ::autopilotrpc::QueryScoresResponse_HeuristicResult& QueryScoresResponse::results(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:autopilotrpc.QueryScoresResponse.results)
  return _internal_results().Get(index);
}
inline ::autopilotrpc::QueryScoresResponse_HeuristicResult* QueryScoresResponse::add_results() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::autopilotrpc::QueryScoresResponse_HeuristicResult* _add = _internal_mutable_results()->Add();
  // @@protoc_insertion_point(field_add:autopilotrpc.QueryScoresResponse.results)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::autopilotrpc::QueryScoresResponse_HeuristicResult>& QueryScoresResponse::results() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:autopilotrpc.QueryScoresResponse.results)
  return _internal_results();
}
inline const ::google::protobuf::RepeatedPtrField<::autopilotrpc::QueryScoresResponse_HeuristicResult>&
QueryScoresResponse::_internal_results() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.results_;
}
inline ::google::protobuf::RepeatedPtrField<::autopilotrpc::QueryScoresResponse_HeuristicResult>*
QueryScoresResponse::_internal_mutable_results() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.results_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// SetScoresRequest

// string heuristic = 1;
inline void SetScoresRequest::clear_heuristic() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heuristic_.ClearToEmpty();
}
inline const std::string& SetScoresRequest::heuristic() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:autopilotrpc.SetScoresRequest.heuristic)
  return _internal_heuristic();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SetScoresRequest::set_heuristic(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heuristic_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:autopilotrpc.SetScoresRequest.heuristic)
}
inline std::string* SetScoresRequest::mutable_heuristic() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_heuristic();
  // @@protoc_insertion_point(field_mutable:autopilotrpc.SetScoresRequest.heuristic)
  return _s;
}
inline const std::string& SetScoresRequest::_internal_heuristic() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.heuristic_.Get();
}
inline void SetScoresRequest::_internal_set_heuristic(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heuristic_.Set(value, GetArena());
}
inline std::string* SetScoresRequest::_internal_mutable_heuristic() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.heuristic_.Mutable( GetArena());
}
inline std::string* SetScoresRequest::release_heuristic() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:autopilotrpc.SetScoresRequest.heuristic)
  return _impl_.heuristic_.Release();
}
inline void SetScoresRequest::set_allocated_heuristic(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.heuristic_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.heuristic_.IsDefault()) {
          _impl_.heuristic_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:autopilotrpc.SetScoresRequest.heuristic)
}

// map<string, double> scores = 2;
inline int SetScoresRequest::_internal_scores_size() const {
  return _internal_scores().size();
}
inline int SetScoresRequest::scores_size() const {
  return _internal_scores_size();
}
inline void SetScoresRequest::clear_scores() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scores_.Clear();
}
inline const ::google::protobuf::Map<std::string, double>& SetScoresRequest::_internal_scores() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scores_.GetMap();
}
inline const ::google::protobuf::Map<std::string, double>& SetScoresRequest::scores() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:autopilotrpc.SetScoresRequest.scores)
  return _internal_scores();
}
inline ::google::protobuf::Map<std::string, double>* SetScoresRequest::_internal_mutable_scores() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.scores_.MutableMap();
}
inline ::google::protobuf::Map<std::string, double>* SetScoresRequest::mutable_scores() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:autopilotrpc.SetScoresRequest.scores)
  return _internal_mutable_scores();
}

// -------------------------------------------------------------------

// SetScoresResponse

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace autopilotrpc


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_autopilot_2eproto_2epb_2eh
