// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chainkit.proto
// Protobuf C++ Version: 5.28.2

#include "chainkit.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace chainrpc {

inline constexpr GetBlockResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : raw_block_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetBlockResponse::GetBlockResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetBlockResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetBlockResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetBlockResponseDefaultTypeInternal() {}
  union {
    GetBlockResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetBlockResponseDefaultTypeInternal _GetBlockResponse_default_instance_;

inline constexpr GetBlockRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : block_hash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetBlockRequest::GetBlockRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetBlockRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetBlockRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetBlockRequestDefaultTypeInternal() {}
  union {
    GetBlockRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetBlockRequestDefaultTypeInternal _GetBlockRequest_default_instance_;

inline constexpr GetBlockHeaderResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : raw_block_header_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetBlockHeaderResponse::GetBlockHeaderResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetBlockHeaderResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetBlockHeaderResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetBlockHeaderResponseDefaultTypeInternal() {}
  union {
    GetBlockHeaderResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetBlockHeaderResponseDefaultTypeInternal _GetBlockHeaderResponse_default_instance_;

inline constexpr GetBlockHeaderRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : block_hash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetBlockHeaderRequest::GetBlockHeaderRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetBlockHeaderRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetBlockHeaderRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetBlockHeaderRequestDefaultTypeInternal() {}
  union {
    GetBlockHeaderRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetBlockHeaderRequestDefaultTypeInternal _GetBlockHeaderRequest_default_instance_;

inline constexpr GetBlockHashResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : block_hash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetBlockHashResponse::GetBlockHashResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetBlockHashResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetBlockHashResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetBlockHashResponseDefaultTypeInternal() {}
  union {
    GetBlockHashResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetBlockHashResponseDefaultTypeInternal _GetBlockHashResponse_default_instance_;

inline constexpr GetBlockHashRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : block_height_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetBlockHashRequest::GetBlockHashRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetBlockHashRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetBlockHashRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetBlockHashRequestDefaultTypeInternal() {}
  union {
    GetBlockHashRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetBlockHashRequestDefaultTypeInternal _GetBlockHashRequest_default_instance_;

inline constexpr GetBestBlockResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : block_hash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        block_height_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetBestBlockResponse::GetBestBlockResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetBestBlockResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetBestBlockResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetBestBlockResponseDefaultTypeInternal() {}
  union {
    GetBestBlockResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetBestBlockResponseDefaultTypeInternal _GetBestBlockResponse_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR GetBestBlockRequest::GetBestBlockRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct GetBestBlockRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetBestBlockRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetBestBlockRequestDefaultTypeInternal() {}
  union {
    GetBestBlockRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetBestBlockRequestDefaultTypeInternal _GetBestBlockRequest_default_instance_;
}  // namespace chainrpc
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_chainkit_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_chainkit_2eproto = nullptr;
const ::uint32_t
    TableStruct_chainkit_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::chainrpc::GetBlockRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::chainrpc::GetBlockRequest, _impl_.block_hash_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::chainrpc::GetBlockResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::chainrpc::GetBlockResponse, _impl_.raw_block_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::chainrpc::GetBlockHeaderRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::chainrpc::GetBlockHeaderRequest, _impl_.block_hash_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::chainrpc::GetBlockHeaderResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::chainrpc::GetBlockHeaderResponse, _impl_.raw_block_header_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::chainrpc::GetBestBlockRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::chainrpc::GetBestBlockResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::chainrpc::GetBestBlockResponse, _impl_.block_hash_),
        PROTOBUF_FIELD_OFFSET(::chainrpc::GetBestBlockResponse, _impl_.block_height_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::chainrpc::GetBlockHashRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::chainrpc::GetBlockHashRequest, _impl_.block_height_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::chainrpc::GetBlockHashResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::chainrpc::GetBlockHashResponse, _impl_.block_hash_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::chainrpc::GetBlockRequest)},
        {9, -1, -1, sizeof(::chainrpc::GetBlockResponse)},
        {18, -1, -1, sizeof(::chainrpc::GetBlockHeaderRequest)},
        {27, -1, -1, sizeof(::chainrpc::GetBlockHeaderResponse)},
        {36, -1, -1, sizeof(::chainrpc::GetBestBlockRequest)},
        {44, -1, -1, sizeof(::chainrpc::GetBestBlockResponse)},
        {54, -1, -1, sizeof(::chainrpc::GetBlockHashRequest)},
        {63, -1, -1, sizeof(::chainrpc::GetBlockHashResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::chainrpc::_GetBlockRequest_default_instance_._instance,
    &::chainrpc::_GetBlockResponse_default_instance_._instance,
    &::chainrpc::_GetBlockHeaderRequest_default_instance_._instance,
    &::chainrpc::_GetBlockHeaderResponse_default_instance_._instance,
    &::chainrpc::_GetBestBlockRequest_default_instance_._instance,
    &::chainrpc::_GetBestBlockResponse_default_instance_._instance,
    &::chainrpc::_GetBlockHashRequest_default_instance_._instance,
    &::chainrpc::_GetBlockHashResponse_default_instance_._instance,
};
const char descriptor_table_protodef_chainkit_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016chainkit.proto\022\010chainrpc\"%\n\017GetBlockRe"
    "quest\022\022\n\nblock_hash\030\001 \001(\014\"%\n\020GetBlockRes"
    "ponse\022\021\n\traw_block\030\001 \001(\014\"+\n\025GetBlockHead"
    "erRequest\022\022\n\nblock_hash\030\001 \001(\014\"2\n\026GetBloc"
    "kHeaderResponse\022\030\n\020raw_block_header\030\001 \001("
    "\014\"\025\n\023GetBestBlockRequest\"@\n\024GetBestBlock"
    "Response\022\022\n\nblock_hash\030\001 \001(\014\022\024\n\014block_he"
    "ight\030\002 \001(\005\"+\n\023GetBlockHashRequest\022\024\n\014blo"
    "ck_height\030\001 \001(\003\"*\n\024GetBlockHashResponse\022"
    "\022\n\nblock_hash\030\001 \001(\0142\300\002\n\010ChainKit\022A\n\010GetB"
    "lock\022\031.chainrpc.GetBlockRequest\032\032.chainr"
    "pc.GetBlockResponse\022S\n\016GetBlockHeader\022\037."
    "chainrpc.GetBlockHeaderRequest\032 .chainrp"
    "c.GetBlockHeaderResponse\022M\n\014GetBestBlock"
    "\022\035.chainrpc.GetBestBlockRequest\032\036.chainr"
    "pc.GetBestBlockResponse\022M\n\014GetBlockHash\022"
    "\035.chainrpc.GetBlockHashRequest\032\036.chainrp"
    "c.GetBlockHashResponseB0Z.github.com/lig"
    "htningnetwork/lnd/lnrpc/chainrpcb\006proto3"
};
static ::absl::once_flag descriptor_table_chainkit_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_chainkit_2eproto = {
    false,
    false,
    760,
    descriptor_table_protodef_chainkit_2eproto,
    "chainkit.proto",
    &descriptor_table_chainkit_2eproto_once,
    nullptr,
    0,
    8,
    schemas,
    file_default_instances,
    TableStruct_chainkit_2eproto::offsets,
    file_level_enum_descriptors_chainkit_2eproto,
    file_level_service_descriptors_chainkit_2eproto,
};
namespace chainrpc {
// ===================================================================

class GetBlockRequest::_Internal {
 public:
};

GetBlockRequest::GetBlockRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:chainrpc.GetBlockRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetBlockRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::chainrpc::GetBlockRequest& from_msg)
      : block_hash_(arena, from.block_hash_),
        _cached_size_{0} {}

GetBlockRequest::GetBlockRequest(
    ::google::protobuf::Arena* arena,
    const GetBlockRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetBlockRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:chainrpc.GetBlockRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetBlockRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : block_hash_(arena),
        _cached_size_{0} {}

inline void GetBlockRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetBlockRequest::~GetBlockRequest() {
  // @@protoc_insertion_point(destructor:chainrpc.GetBlockRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetBlockRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.block_hash_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetBlockRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetBlockRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetBlockRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetBlockRequest>(),
            ::google::protobuf::Message::GetNewImpl<GetBlockRequest>(),
            ::google::protobuf::Message::GetClearImpl<GetBlockRequest>(), &GetBlockRequest::ByteSizeLong,
                &GetBlockRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetBlockRequest, _impl_._cached_size_),
            false,
        },
        &GetBlockRequest::kDescriptorMethods,
        &descriptor_table_chainkit_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetBlockRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GetBlockRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::chainrpc::GetBlockRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes block_hash = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetBlockRequest, _impl_.block_hash_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes block_hash = 1;
    {PROTOBUF_FIELD_OFFSET(GetBlockRequest, _impl_.block_hash_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GetBlockRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:chainrpc.GetBlockRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.block_hash_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetBlockRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetBlockRequest& this_ = static_cast<const GetBlockRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetBlockRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetBlockRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:chainrpc.GetBlockRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes block_hash = 1;
          if (!this_._internal_block_hash().empty()) {
            const std::string& _s = this_._internal_block_hash();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:chainrpc.GetBlockRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetBlockRequest::ByteSizeLong(const MessageLite& base) {
          const GetBlockRequest& this_ = static_cast<const GetBlockRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetBlockRequest::ByteSizeLong() const {
          const GetBlockRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:chainrpc.GetBlockRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bytes block_hash = 1;
            if (!this_._internal_block_hash().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_block_hash());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetBlockRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetBlockRequest*>(&to_msg);
  auto& from = static_cast<const GetBlockRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chainrpc.GetBlockRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_block_hash().empty()) {
    _this->_internal_set_block_hash(from._internal_block_hash());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetBlockRequest::CopyFrom(const GetBlockRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chainrpc.GetBlockRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetBlockRequest::InternalSwap(GetBlockRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.block_hash_, &other->_impl_.block_hash_, arena);
}

::google::protobuf::Metadata GetBlockRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetBlockResponse::_Internal {
 public:
};

GetBlockResponse::GetBlockResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:chainrpc.GetBlockResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetBlockResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::chainrpc::GetBlockResponse& from_msg)
      : raw_block_(arena, from.raw_block_),
        _cached_size_{0} {}

GetBlockResponse::GetBlockResponse(
    ::google::protobuf::Arena* arena,
    const GetBlockResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetBlockResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:chainrpc.GetBlockResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetBlockResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : raw_block_(arena),
        _cached_size_{0} {}

inline void GetBlockResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetBlockResponse::~GetBlockResponse() {
  // @@protoc_insertion_point(destructor:chainrpc.GetBlockResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetBlockResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.raw_block_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetBlockResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetBlockResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetBlockResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetBlockResponse>(),
            ::google::protobuf::Message::GetNewImpl<GetBlockResponse>(),
            ::google::protobuf::Message::GetClearImpl<GetBlockResponse>(), &GetBlockResponse::ByteSizeLong,
                &GetBlockResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetBlockResponse, _impl_._cached_size_),
            false,
        },
        &GetBlockResponse::kDescriptorMethods,
        &descriptor_table_chainkit_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetBlockResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GetBlockResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::chainrpc::GetBlockResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes raw_block = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetBlockResponse, _impl_.raw_block_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes raw_block = 1;
    {PROTOBUF_FIELD_OFFSET(GetBlockResponse, _impl_.raw_block_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GetBlockResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:chainrpc.GetBlockResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.raw_block_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetBlockResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetBlockResponse& this_ = static_cast<const GetBlockResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetBlockResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetBlockResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:chainrpc.GetBlockResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes raw_block = 1;
          if (!this_._internal_raw_block().empty()) {
            const std::string& _s = this_._internal_raw_block();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:chainrpc.GetBlockResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetBlockResponse::ByteSizeLong(const MessageLite& base) {
          const GetBlockResponse& this_ = static_cast<const GetBlockResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetBlockResponse::ByteSizeLong() const {
          const GetBlockResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:chainrpc.GetBlockResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bytes raw_block = 1;
            if (!this_._internal_raw_block().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_raw_block());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetBlockResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetBlockResponse*>(&to_msg);
  auto& from = static_cast<const GetBlockResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chainrpc.GetBlockResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_raw_block().empty()) {
    _this->_internal_set_raw_block(from._internal_raw_block());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetBlockResponse::CopyFrom(const GetBlockResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chainrpc.GetBlockResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetBlockResponse::InternalSwap(GetBlockResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.raw_block_, &other->_impl_.raw_block_, arena);
}

::google::protobuf::Metadata GetBlockResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetBlockHeaderRequest::_Internal {
 public:
};

GetBlockHeaderRequest::GetBlockHeaderRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:chainrpc.GetBlockHeaderRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetBlockHeaderRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::chainrpc::GetBlockHeaderRequest& from_msg)
      : block_hash_(arena, from.block_hash_),
        _cached_size_{0} {}

GetBlockHeaderRequest::GetBlockHeaderRequest(
    ::google::protobuf::Arena* arena,
    const GetBlockHeaderRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetBlockHeaderRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:chainrpc.GetBlockHeaderRequest)
}
inline PROTOBUF_NDEBUG_INLINE GetBlockHeaderRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : block_hash_(arena),
        _cached_size_{0} {}

inline void GetBlockHeaderRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetBlockHeaderRequest::~GetBlockHeaderRequest() {
  // @@protoc_insertion_point(destructor:chainrpc.GetBlockHeaderRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetBlockHeaderRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.block_hash_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetBlockHeaderRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetBlockHeaderRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetBlockHeaderRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetBlockHeaderRequest>(),
            ::google::protobuf::Message::GetNewImpl<GetBlockHeaderRequest>(),
            ::google::protobuf::Message::GetClearImpl<GetBlockHeaderRequest>(), &GetBlockHeaderRequest::ByteSizeLong,
                &GetBlockHeaderRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetBlockHeaderRequest, _impl_._cached_size_),
            false,
        },
        &GetBlockHeaderRequest::kDescriptorMethods,
        &descriptor_table_chainkit_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetBlockHeaderRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GetBlockHeaderRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::chainrpc::GetBlockHeaderRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes block_hash = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetBlockHeaderRequest, _impl_.block_hash_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes block_hash = 1;
    {PROTOBUF_FIELD_OFFSET(GetBlockHeaderRequest, _impl_.block_hash_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GetBlockHeaderRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:chainrpc.GetBlockHeaderRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.block_hash_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetBlockHeaderRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetBlockHeaderRequest& this_ = static_cast<const GetBlockHeaderRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetBlockHeaderRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetBlockHeaderRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:chainrpc.GetBlockHeaderRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes block_hash = 1;
          if (!this_._internal_block_hash().empty()) {
            const std::string& _s = this_._internal_block_hash();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:chainrpc.GetBlockHeaderRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetBlockHeaderRequest::ByteSizeLong(const MessageLite& base) {
          const GetBlockHeaderRequest& this_ = static_cast<const GetBlockHeaderRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetBlockHeaderRequest::ByteSizeLong() const {
          const GetBlockHeaderRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:chainrpc.GetBlockHeaderRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bytes block_hash = 1;
            if (!this_._internal_block_hash().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_block_hash());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetBlockHeaderRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetBlockHeaderRequest*>(&to_msg);
  auto& from = static_cast<const GetBlockHeaderRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chainrpc.GetBlockHeaderRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_block_hash().empty()) {
    _this->_internal_set_block_hash(from._internal_block_hash());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetBlockHeaderRequest::CopyFrom(const GetBlockHeaderRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chainrpc.GetBlockHeaderRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetBlockHeaderRequest::InternalSwap(GetBlockHeaderRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.block_hash_, &other->_impl_.block_hash_, arena);
}

::google::protobuf::Metadata GetBlockHeaderRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetBlockHeaderResponse::_Internal {
 public:
};

GetBlockHeaderResponse::GetBlockHeaderResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:chainrpc.GetBlockHeaderResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetBlockHeaderResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::chainrpc::GetBlockHeaderResponse& from_msg)
      : raw_block_header_(arena, from.raw_block_header_),
        _cached_size_{0} {}

GetBlockHeaderResponse::GetBlockHeaderResponse(
    ::google::protobuf::Arena* arena,
    const GetBlockHeaderResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetBlockHeaderResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:chainrpc.GetBlockHeaderResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetBlockHeaderResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : raw_block_header_(arena),
        _cached_size_{0} {}

inline void GetBlockHeaderResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetBlockHeaderResponse::~GetBlockHeaderResponse() {
  // @@protoc_insertion_point(destructor:chainrpc.GetBlockHeaderResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetBlockHeaderResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.raw_block_header_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetBlockHeaderResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetBlockHeaderResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetBlockHeaderResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetBlockHeaderResponse>(),
            ::google::protobuf::Message::GetNewImpl<GetBlockHeaderResponse>(),
            ::google::protobuf::Message::GetClearImpl<GetBlockHeaderResponse>(), &GetBlockHeaderResponse::ByteSizeLong,
                &GetBlockHeaderResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetBlockHeaderResponse, _impl_._cached_size_),
            false,
        },
        &GetBlockHeaderResponse::kDescriptorMethods,
        &descriptor_table_chainkit_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetBlockHeaderResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GetBlockHeaderResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::chainrpc::GetBlockHeaderResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes raw_block_header = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetBlockHeaderResponse, _impl_.raw_block_header_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes raw_block_header = 1;
    {PROTOBUF_FIELD_OFFSET(GetBlockHeaderResponse, _impl_.raw_block_header_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GetBlockHeaderResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:chainrpc.GetBlockHeaderResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.raw_block_header_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetBlockHeaderResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetBlockHeaderResponse& this_ = static_cast<const GetBlockHeaderResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetBlockHeaderResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetBlockHeaderResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:chainrpc.GetBlockHeaderResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes raw_block_header = 1;
          if (!this_._internal_raw_block_header().empty()) {
            const std::string& _s = this_._internal_raw_block_header();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:chainrpc.GetBlockHeaderResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetBlockHeaderResponse::ByteSizeLong(const MessageLite& base) {
          const GetBlockHeaderResponse& this_ = static_cast<const GetBlockHeaderResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetBlockHeaderResponse::ByteSizeLong() const {
          const GetBlockHeaderResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:chainrpc.GetBlockHeaderResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bytes raw_block_header = 1;
            if (!this_._internal_raw_block_header().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_raw_block_header());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetBlockHeaderResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetBlockHeaderResponse*>(&to_msg);
  auto& from = static_cast<const GetBlockHeaderResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chainrpc.GetBlockHeaderResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_raw_block_header().empty()) {
    _this->_internal_set_raw_block_header(from._internal_raw_block_header());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetBlockHeaderResponse::CopyFrom(const GetBlockHeaderResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chainrpc.GetBlockHeaderResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetBlockHeaderResponse::InternalSwap(GetBlockHeaderResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.raw_block_header_, &other->_impl_.raw_block_header_, arena);
}

::google::protobuf::Metadata GetBlockHeaderResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetBestBlockRequest::_Internal {
 public:
};

GetBestBlockRequest::GetBestBlockRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:chainrpc.GetBestBlockRequest)
}
GetBestBlockRequest::GetBestBlockRequest(
    ::google::protobuf::Arena* arena,
    const GetBestBlockRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetBestBlockRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:chainrpc.GetBestBlockRequest)
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetBestBlockRequest::_class_data_ = {
        ::google::protobuf::internal::ZeroFieldsBase::ClassData{
            &_GetBestBlockRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetBestBlockRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::internal::ZeroFieldsBase::GetDeleteImpl<GetBestBlockRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<GetBestBlockRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<GetBestBlockRequest>(), &GetBestBlockRequest::ByteSizeLong,
                &GetBestBlockRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetBestBlockRequest, _impl_._cached_size_),
            false,
        },
        &GetBestBlockRequest::kDescriptorMethods,
        &descriptor_table_chainkit_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetBestBlockRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> GetBestBlockRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::chainrpc::GetBestBlockRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata GetBestBlockRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetBestBlockResponse::_Internal {
 public:
};

GetBestBlockResponse::GetBestBlockResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:chainrpc.GetBestBlockResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetBestBlockResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::chainrpc::GetBestBlockResponse& from_msg)
      : block_hash_(arena, from.block_hash_),
        _cached_size_{0} {}

GetBestBlockResponse::GetBestBlockResponse(
    ::google::protobuf::Arena* arena,
    const GetBestBlockResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetBestBlockResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.block_height_ = from._impl_.block_height_;

  // @@protoc_insertion_point(copy_constructor:chainrpc.GetBestBlockResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetBestBlockResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : block_hash_(arena),
        _cached_size_{0} {}

inline void GetBestBlockResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.block_height_ = {};
}
GetBestBlockResponse::~GetBestBlockResponse() {
  // @@protoc_insertion_point(destructor:chainrpc.GetBestBlockResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetBestBlockResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.block_hash_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetBestBlockResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetBestBlockResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetBestBlockResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetBestBlockResponse>(),
            ::google::protobuf::Message::GetNewImpl<GetBestBlockResponse>(),
            ::google::protobuf::Message::GetClearImpl<GetBestBlockResponse>(), &GetBestBlockResponse::ByteSizeLong,
                &GetBestBlockResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetBestBlockResponse, _impl_._cached_size_),
            false,
        },
        &GetBestBlockResponse::kDescriptorMethods,
        &descriptor_table_chainkit_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetBestBlockResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> GetBestBlockResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::chainrpc::GetBestBlockResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 block_height = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetBestBlockResponse, _impl_.block_height_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(GetBestBlockResponse, _impl_.block_height_)}},
    // bytes block_hash = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetBestBlockResponse, _impl_.block_hash_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes block_hash = 1;
    {PROTOBUF_FIELD_OFFSET(GetBestBlockResponse, _impl_.block_hash_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // int32 block_height = 2;
    {PROTOBUF_FIELD_OFFSET(GetBestBlockResponse, _impl_.block_height_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GetBestBlockResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:chainrpc.GetBestBlockResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.block_hash_.ClearToEmpty();
  _impl_.block_height_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetBestBlockResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetBestBlockResponse& this_ = static_cast<const GetBestBlockResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetBestBlockResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetBestBlockResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:chainrpc.GetBestBlockResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes block_hash = 1;
          if (!this_._internal_block_hash().empty()) {
            const std::string& _s = this_._internal_block_hash();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          // int32 block_height = 2;
          if (this_._internal_block_height() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_block_height(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:chainrpc.GetBestBlockResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetBestBlockResponse::ByteSizeLong(const MessageLite& base) {
          const GetBestBlockResponse& this_ = static_cast<const GetBestBlockResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetBestBlockResponse::ByteSizeLong() const {
          const GetBestBlockResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:chainrpc.GetBestBlockResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes block_hash = 1;
            if (!this_._internal_block_hash().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_block_hash());
            }
            // int32 block_height = 2;
            if (this_._internal_block_height() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_block_height());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetBestBlockResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetBestBlockResponse*>(&to_msg);
  auto& from = static_cast<const GetBestBlockResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chainrpc.GetBestBlockResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_block_hash().empty()) {
    _this->_internal_set_block_hash(from._internal_block_hash());
  }
  if (from._internal_block_height() != 0) {
    _this->_impl_.block_height_ = from._impl_.block_height_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetBestBlockResponse::CopyFrom(const GetBestBlockResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chainrpc.GetBestBlockResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetBestBlockResponse::InternalSwap(GetBestBlockResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.block_hash_, &other->_impl_.block_hash_, arena);
        swap(_impl_.block_height_, other->_impl_.block_height_);
}

::google::protobuf::Metadata GetBestBlockResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetBlockHashRequest::_Internal {
 public:
};

GetBlockHashRequest::GetBlockHashRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:chainrpc.GetBlockHashRequest)
}
GetBlockHashRequest::GetBlockHashRequest(
    ::google::protobuf::Arena* arena, const GetBlockHashRequest& from)
    : GetBlockHashRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE GetBlockHashRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GetBlockHashRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.block_height_ = {};
}
GetBlockHashRequest::~GetBlockHashRequest() {
  // @@protoc_insertion_point(destructor:chainrpc.GetBlockHashRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetBlockHashRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetBlockHashRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetBlockHashRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetBlockHashRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetBlockHashRequest>(),
            ::google::protobuf::Message::GetNewImpl<GetBlockHashRequest>(),
            ::google::protobuf::Message::GetClearImpl<GetBlockHashRequest>(), &GetBlockHashRequest::ByteSizeLong,
                &GetBlockHashRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetBlockHashRequest, _impl_._cached_size_),
            false,
        },
        &GetBlockHashRequest::kDescriptorMethods,
        &descriptor_table_chainkit_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetBlockHashRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GetBlockHashRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::chainrpc::GetBlockHashRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 block_height = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(GetBlockHashRequest, _impl_.block_height_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GetBlockHashRequest, _impl_.block_height_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 block_height = 1;
    {PROTOBUF_FIELD_OFFSET(GetBlockHashRequest, _impl_.block_height_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GetBlockHashRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:chainrpc.GetBlockHashRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.block_height_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetBlockHashRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetBlockHashRequest& this_ = static_cast<const GetBlockHashRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetBlockHashRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetBlockHashRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:chainrpc.GetBlockHashRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int64 block_height = 1;
          if (this_._internal_block_height() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<1>(
                    stream, this_._internal_block_height(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:chainrpc.GetBlockHashRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetBlockHashRequest::ByteSizeLong(const MessageLite& base) {
          const GetBlockHashRequest& this_ = static_cast<const GetBlockHashRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetBlockHashRequest::ByteSizeLong() const {
          const GetBlockHashRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:chainrpc.GetBlockHashRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int64 block_height = 1;
            if (this_._internal_block_height() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_block_height());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetBlockHashRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetBlockHashRequest*>(&to_msg);
  auto& from = static_cast<const GetBlockHashRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chainrpc.GetBlockHashRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_block_height() != 0) {
    _this->_impl_.block_height_ = from._impl_.block_height_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetBlockHashRequest::CopyFrom(const GetBlockHashRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chainrpc.GetBlockHashRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetBlockHashRequest::InternalSwap(GetBlockHashRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.block_height_, other->_impl_.block_height_);
}

::google::protobuf::Metadata GetBlockHashRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetBlockHashResponse::_Internal {
 public:
};

GetBlockHashResponse::GetBlockHashResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:chainrpc.GetBlockHashResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetBlockHashResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::chainrpc::GetBlockHashResponse& from_msg)
      : block_hash_(arena, from.block_hash_),
        _cached_size_{0} {}

GetBlockHashResponse::GetBlockHashResponse(
    ::google::protobuf::Arena* arena,
    const GetBlockHashResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetBlockHashResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:chainrpc.GetBlockHashResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetBlockHashResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : block_hash_(arena),
        _cached_size_{0} {}

inline void GetBlockHashResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetBlockHashResponse::~GetBlockHashResponse() {
  // @@protoc_insertion_point(destructor:chainrpc.GetBlockHashResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetBlockHashResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.block_hash_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GetBlockHashResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GetBlockHashResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GetBlockHashResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GetBlockHashResponse>(),
            ::google::protobuf::Message::GetNewImpl<GetBlockHashResponse>(),
            ::google::protobuf::Message::GetClearImpl<GetBlockHashResponse>(), &GetBlockHashResponse::ByteSizeLong,
                &GetBlockHashResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GetBlockHashResponse, _impl_._cached_size_),
            false,
        },
        &GetBlockHashResponse::kDescriptorMethods,
        &descriptor_table_chainkit_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GetBlockHashResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GetBlockHashResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::chainrpc::GetBlockHashResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes block_hash = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetBlockHashResponse, _impl_.block_hash_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes block_hash = 1;
    {PROTOBUF_FIELD_OFFSET(GetBlockHashResponse, _impl_.block_hash_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GetBlockHashResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:chainrpc.GetBlockHashResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.block_hash_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetBlockHashResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetBlockHashResponse& this_ = static_cast<const GetBlockHashResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetBlockHashResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetBlockHashResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:chainrpc.GetBlockHashResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes block_hash = 1;
          if (!this_._internal_block_hash().empty()) {
            const std::string& _s = this_._internal_block_hash();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:chainrpc.GetBlockHashResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetBlockHashResponse::ByteSizeLong(const MessageLite& base) {
          const GetBlockHashResponse& this_ = static_cast<const GetBlockHashResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetBlockHashResponse::ByteSizeLong() const {
          const GetBlockHashResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:chainrpc.GetBlockHashResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bytes block_hash = 1;
            if (!this_._internal_block_hash().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_block_hash());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetBlockHashResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetBlockHashResponse*>(&to_msg);
  auto& from = static_cast<const GetBlockHashResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:chainrpc.GetBlockHashResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_block_hash().empty()) {
    _this->_internal_set_block_hash(from._internal_block_hash());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetBlockHashResponse::CopyFrom(const GetBlockHashResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:chainrpc.GetBlockHashResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetBlockHashResponse::InternalSwap(GetBlockHashResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.block_hash_, &other->_impl_.block_hash_, arena);
}

::google::protobuf::Metadata GetBlockHashResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace chainrpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_chainkit_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
