// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: peers.proto
// Protobuf C++ Version: 5.28.2

#include "peers.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace peersrpc {

inline constexpr UpdateFeatureAction::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : action_{static_cast< ::peersrpc::UpdateAction >(0)},
        feature_bit_{static_cast< ::lnrpc::FeatureBit >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UpdateFeatureAction::UpdateFeatureAction(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateFeatureActionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateFeatureActionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateFeatureActionDefaultTypeInternal() {}
  union {
    UpdateFeatureAction _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateFeatureActionDefaultTypeInternal _UpdateFeatureAction_default_instance_;

inline constexpr UpdateAddressAction::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : address_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        action_{static_cast< ::peersrpc::UpdateAction >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UpdateAddressAction::UpdateAddressAction(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateAddressActionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateAddressActionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateAddressActionDefaultTypeInternal() {}
  union {
    UpdateAddressAction _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateAddressActionDefaultTypeInternal _UpdateAddressAction_default_instance_;

inline constexpr NodeAnnouncementUpdateResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : ops_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NodeAnnouncementUpdateResponse::NodeAnnouncementUpdateResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NodeAnnouncementUpdateResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NodeAnnouncementUpdateResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NodeAnnouncementUpdateResponseDefaultTypeInternal() {}
  union {
    NodeAnnouncementUpdateResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NodeAnnouncementUpdateResponseDefaultTypeInternal _NodeAnnouncementUpdateResponse_default_instance_;

inline constexpr NodeAnnouncementUpdateRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : feature_updates_{},
        address_updates_{},
        color_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        alias_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NodeAnnouncementUpdateRequest::NodeAnnouncementUpdateRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NodeAnnouncementUpdateRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NodeAnnouncementUpdateRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NodeAnnouncementUpdateRequestDefaultTypeInternal() {}
  union {
    NodeAnnouncementUpdateRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NodeAnnouncementUpdateRequestDefaultTypeInternal _NodeAnnouncementUpdateRequest_default_instance_;
}  // namespace peersrpc
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_peers_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_peers_2eproto = nullptr;
const ::uint32_t
    TableStruct_peers_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::peersrpc::UpdateAddressAction, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::peersrpc::UpdateAddressAction, _impl_.action_),
        PROTOBUF_FIELD_OFFSET(::peersrpc::UpdateAddressAction, _impl_.address_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::peersrpc::UpdateFeatureAction, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::peersrpc::UpdateFeatureAction, _impl_.action_),
        PROTOBUF_FIELD_OFFSET(::peersrpc::UpdateFeatureAction, _impl_.feature_bit_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::peersrpc::NodeAnnouncementUpdateRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::peersrpc::NodeAnnouncementUpdateRequest, _impl_.feature_updates_),
        PROTOBUF_FIELD_OFFSET(::peersrpc::NodeAnnouncementUpdateRequest, _impl_.color_),
        PROTOBUF_FIELD_OFFSET(::peersrpc::NodeAnnouncementUpdateRequest, _impl_.alias_),
        PROTOBUF_FIELD_OFFSET(::peersrpc::NodeAnnouncementUpdateRequest, _impl_.address_updates_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::peersrpc::NodeAnnouncementUpdateResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::peersrpc::NodeAnnouncementUpdateResponse, _impl_.ops_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::peersrpc::UpdateAddressAction)},
        {10, -1, -1, sizeof(::peersrpc::UpdateFeatureAction)},
        {20, -1, -1, sizeof(::peersrpc::NodeAnnouncementUpdateRequest)},
        {32, -1, -1, sizeof(::peersrpc::NodeAnnouncementUpdateResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::peersrpc::_UpdateAddressAction_default_instance_._instance,
    &::peersrpc::_UpdateFeatureAction_default_instance_._instance,
    &::peersrpc::_NodeAnnouncementUpdateRequest_default_instance_._instance,
    &::peersrpc::_NodeAnnouncementUpdateResponse_default_instance_._instance,
};
const char descriptor_table_protodef_peers_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013peers.proto\022\010peersrpc\032\017lightning.proto"
    "\"N\n\023UpdateAddressAction\022&\n\006action\030\001 \001(\0162"
    "\026.peersrpc.UpdateAction\022\017\n\007address\030\002 \001(\t"
    "\"e\n\023UpdateFeatureAction\022&\n\006action\030\001 \001(\0162"
    "\026.peersrpc.UpdateAction\022&\n\013feature_bit\030\002"
    " \001(\0162\021.lnrpc.FeatureBit\"\255\001\n\035NodeAnnounce"
    "mentUpdateRequest\0226\n\017feature_updates\030\001 \003"
    "(\0132\035.peersrpc.UpdateFeatureAction\022\r\n\005col"
    "or\030\002 \001(\t\022\r\n\005alias\030\003 \001(\t\0226\n\017address_updat"
    "es\030\004 \003(\0132\035.peersrpc.UpdateAddressAction\""
    "8\n\036NodeAnnouncementUpdateResponse\022\026\n\003ops"
    "\030\001 \003(\0132\t.lnrpc.Op*#\n\014UpdateAction\022\007\n\003ADD"
    "\020\000\022\n\n\006REMOVE\020\001*i\n\nFeatureSet\022\014\n\010SET_INIT"
    "\020\000\022\025\n\021SET_LEGACY_GLOBAL\020\001\022\020\n\014SET_NODE_AN"
    "N\020\002\022\017\n\013SET_INVOICE\020\003\022\023\n\017SET_INVOICE_AMP\020"
    "\0042t\n\005Peers\022k\n\026UpdateNodeAnnouncement\022\'.p"
    "eersrpc.NodeAnnouncementUpdateRequest\032(."
    "peersrpc.NodeAnnouncementUpdateResponseB"
    "0Z.github.com/lightningnetwork/lnd/lnrpc"
    "/peersrpcb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_peers_2eproto_deps[1] =
    {
        &::descriptor_table_lightning_2eproto,
};
static ::absl::once_flag descriptor_table_peers_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_peers_2eproto = {
    false,
    false,
    777,
    descriptor_table_protodef_peers_2eproto,
    "peers.proto",
    &descriptor_table_peers_2eproto_once,
    descriptor_table_peers_2eproto_deps,
    1,
    4,
    schemas,
    file_default_instances,
    TableStruct_peers_2eproto::offsets,
    file_level_enum_descriptors_peers_2eproto,
    file_level_service_descriptors_peers_2eproto,
};
namespace peersrpc {
const ::google::protobuf::EnumDescriptor* UpdateAction_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_peers_2eproto);
  return file_level_enum_descriptors_peers_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t UpdateAction_internal_data_[] = {
    131072u, 0u, };
bool UpdateAction_IsValid(int value) {
  return 0 <= value && value <= 1;
}
const ::google::protobuf::EnumDescriptor* FeatureSet_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_peers_2eproto);
  return file_level_enum_descriptors_peers_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t FeatureSet_internal_data_[] = {
    327680u, 0u, };
bool FeatureSet_IsValid(int value) {
  return 0 <= value && value <= 4;
}
// ===================================================================

class UpdateAddressAction::_Internal {
 public:
};

UpdateAddressAction::UpdateAddressAction(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:peersrpc.UpdateAddressAction)
}
inline PROTOBUF_NDEBUG_INLINE UpdateAddressAction::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::peersrpc::UpdateAddressAction& from_msg)
      : address_(arena, from.address_),
        _cached_size_{0} {}

UpdateAddressAction::UpdateAddressAction(
    ::google::protobuf::Arena* arena,
    const UpdateAddressAction& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UpdateAddressAction* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.action_ = from._impl_.action_;

  // @@protoc_insertion_point(copy_constructor:peersrpc.UpdateAddressAction)
}
inline PROTOBUF_NDEBUG_INLINE UpdateAddressAction::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : address_(arena),
        _cached_size_{0} {}

inline void UpdateAddressAction::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.action_ = {};
}
UpdateAddressAction::~UpdateAddressAction() {
  // @@protoc_insertion_point(destructor:peersrpc.UpdateAddressAction)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UpdateAddressAction::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.address_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    UpdateAddressAction::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_UpdateAddressAction_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &UpdateAddressAction::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<UpdateAddressAction>(),
            ::google::protobuf::Message::GetNewImpl<UpdateAddressAction>(),
            ::google::protobuf::Message::GetClearImpl<UpdateAddressAction>(), &UpdateAddressAction::ByteSizeLong,
                &UpdateAddressAction::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(UpdateAddressAction, _impl_._cached_size_),
            false,
        },
        &UpdateAddressAction::kDescriptorMethods,
        &descriptor_table_peers_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* UpdateAddressAction::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 44, 2> UpdateAddressAction::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::peersrpc::UpdateAddressAction>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string address = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateAddressAction, _impl_.address_)}},
    // .peersrpc.UpdateAction action = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UpdateAddressAction, _impl_.action_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateAddressAction, _impl_.action_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .peersrpc.UpdateAction action = 1;
    {PROTOBUF_FIELD_OFFSET(UpdateAddressAction, _impl_.action_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string address = 2;
    {PROTOBUF_FIELD_OFFSET(UpdateAddressAction, _impl_.address_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\34\0\7\0\0\0\0\0"
    "peersrpc.UpdateAddressAction"
    "address"
  }},
};

PROTOBUF_NOINLINE void UpdateAddressAction::Clear() {
// @@protoc_insertion_point(message_clear_start:peersrpc.UpdateAddressAction)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.address_.ClearToEmpty();
  _impl_.action_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UpdateAddressAction::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UpdateAddressAction& this_ = static_cast<const UpdateAddressAction&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UpdateAddressAction::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UpdateAddressAction& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:peersrpc.UpdateAddressAction)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .peersrpc.UpdateAction action = 1;
          if (this_._internal_action() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_action(), target);
          }

          // string address = 2;
          if (!this_._internal_address().empty()) {
            const std::string& _s = this_._internal_address();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "peersrpc.UpdateAddressAction.address");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:peersrpc.UpdateAddressAction)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UpdateAddressAction::ByteSizeLong(const MessageLite& base) {
          const UpdateAddressAction& this_ = static_cast<const UpdateAddressAction&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UpdateAddressAction::ByteSizeLong() const {
          const UpdateAddressAction& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:peersrpc.UpdateAddressAction)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string address = 2;
            if (!this_._internal_address().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_address());
            }
            // .peersrpc.UpdateAction action = 1;
            if (this_._internal_action() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_action());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UpdateAddressAction::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UpdateAddressAction*>(&to_msg);
  auto& from = static_cast<const UpdateAddressAction&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:peersrpc.UpdateAddressAction)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_address().empty()) {
    _this->_internal_set_address(from._internal_address());
  }
  if (from._internal_action() != 0) {
    _this->_impl_.action_ = from._impl_.action_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateAddressAction::CopyFrom(const UpdateAddressAction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:peersrpc.UpdateAddressAction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UpdateAddressAction::InternalSwap(UpdateAddressAction* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.address_, &other->_impl_.address_, arena);
  swap(_impl_.action_, other->_impl_.action_);
}

::google::protobuf::Metadata UpdateAddressAction::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateFeatureAction::_Internal {
 public:
};

UpdateFeatureAction::UpdateFeatureAction(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:peersrpc.UpdateFeatureAction)
}
UpdateFeatureAction::UpdateFeatureAction(
    ::google::protobuf::Arena* arena, const UpdateFeatureAction& from)
    : UpdateFeatureAction(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE UpdateFeatureAction::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void UpdateFeatureAction::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, action_),
           0,
           offsetof(Impl_, feature_bit_) -
               offsetof(Impl_, action_) +
               sizeof(Impl_::feature_bit_));
}
UpdateFeatureAction::~UpdateFeatureAction() {
  // @@protoc_insertion_point(destructor:peersrpc.UpdateFeatureAction)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UpdateFeatureAction::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    UpdateFeatureAction::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_UpdateFeatureAction_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &UpdateFeatureAction::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<UpdateFeatureAction>(),
            ::google::protobuf::Message::GetNewImpl<UpdateFeatureAction>(),
            ::google::protobuf::Message::GetClearImpl<UpdateFeatureAction>(), &UpdateFeatureAction::ByteSizeLong,
                &UpdateFeatureAction::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(UpdateFeatureAction, _impl_._cached_size_),
            false,
        },
        &UpdateFeatureAction::kDescriptorMethods,
        &descriptor_table_peers_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* UpdateFeatureAction::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> UpdateFeatureAction::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::peersrpc::UpdateFeatureAction>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .lnrpc.FeatureBit feature_bit = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UpdateFeatureAction, _impl_.feature_bit_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateFeatureAction, _impl_.feature_bit_)}},
    // .peersrpc.UpdateAction action = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UpdateFeatureAction, _impl_.action_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateFeatureAction, _impl_.action_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .peersrpc.UpdateAction action = 1;
    {PROTOBUF_FIELD_OFFSET(UpdateFeatureAction, _impl_.action_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .lnrpc.FeatureBit feature_bit = 2;
    {PROTOBUF_FIELD_OFFSET(UpdateFeatureAction, _impl_.feature_bit_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void UpdateFeatureAction::Clear() {
// @@protoc_insertion_point(message_clear_start:peersrpc.UpdateFeatureAction)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.action_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.feature_bit_) -
      reinterpret_cast<char*>(&_impl_.action_)) + sizeof(_impl_.feature_bit_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UpdateFeatureAction::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UpdateFeatureAction& this_ = static_cast<const UpdateFeatureAction&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UpdateFeatureAction::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UpdateFeatureAction& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:peersrpc.UpdateFeatureAction)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .peersrpc.UpdateAction action = 1;
          if (this_._internal_action() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_action(), target);
          }

          // .lnrpc.FeatureBit feature_bit = 2;
          if (this_._internal_feature_bit() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_feature_bit(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:peersrpc.UpdateFeatureAction)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UpdateFeatureAction::ByteSizeLong(const MessageLite& base) {
          const UpdateFeatureAction& this_ = static_cast<const UpdateFeatureAction&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UpdateFeatureAction::ByteSizeLong() const {
          const UpdateFeatureAction& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:peersrpc.UpdateFeatureAction)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .peersrpc.UpdateAction action = 1;
            if (this_._internal_action() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_action());
            }
            // .lnrpc.FeatureBit feature_bit = 2;
            if (this_._internal_feature_bit() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_feature_bit());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UpdateFeatureAction::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UpdateFeatureAction*>(&to_msg);
  auto& from = static_cast<const UpdateFeatureAction&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:peersrpc.UpdateFeatureAction)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_action() != 0) {
    _this->_impl_.action_ = from._impl_.action_;
  }
  if (from._internal_feature_bit() != 0) {
    _this->_impl_.feature_bit_ = from._impl_.feature_bit_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateFeatureAction::CopyFrom(const UpdateFeatureAction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:peersrpc.UpdateFeatureAction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UpdateFeatureAction::InternalSwap(UpdateFeatureAction* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UpdateFeatureAction, _impl_.feature_bit_)
      + sizeof(UpdateFeatureAction::_impl_.feature_bit_)
      - PROTOBUF_FIELD_OFFSET(UpdateFeatureAction, _impl_.action_)>(
          reinterpret_cast<char*>(&_impl_.action_),
          reinterpret_cast<char*>(&other->_impl_.action_));
}

::google::protobuf::Metadata UpdateFeatureAction::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NodeAnnouncementUpdateRequest::_Internal {
 public:
};

NodeAnnouncementUpdateRequest::NodeAnnouncementUpdateRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:peersrpc.NodeAnnouncementUpdateRequest)
}
inline PROTOBUF_NDEBUG_INLINE NodeAnnouncementUpdateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::peersrpc::NodeAnnouncementUpdateRequest& from_msg)
      : feature_updates_{visibility, arena, from.feature_updates_},
        address_updates_{visibility, arena, from.address_updates_},
        color_(arena, from.color_),
        alias_(arena, from.alias_),
        _cached_size_{0} {}

NodeAnnouncementUpdateRequest::NodeAnnouncementUpdateRequest(
    ::google::protobuf::Arena* arena,
    const NodeAnnouncementUpdateRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NodeAnnouncementUpdateRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:peersrpc.NodeAnnouncementUpdateRequest)
}
inline PROTOBUF_NDEBUG_INLINE NodeAnnouncementUpdateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : feature_updates_{visibility, arena},
        address_updates_{visibility, arena},
        color_(arena),
        alias_(arena),
        _cached_size_{0} {}

inline void NodeAnnouncementUpdateRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
NodeAnnouncementUpdateRequest::~NodeAnnouncementUpdateRequest() {
  // @@protoc_insertion_point(destructor:peersrpc.NodeAnnouncementUpdateRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void NodeAnnouncementUpdateRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.color_.Destroy();
  _impl_.alias_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    NodeAnnouncementUpdateRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_NodeAnnouncementUpdateRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &NodeAnnouncementUpdateRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<NodeAnnouncementUpdateRequest>(),
            ::google::protobuf::Message::GetNewImpl<NodeAnnouncementUpdateRequest>(),
            ::google::protobuf::Message::GetClearImpl<NodeAnnouncementUpdateRequest>(), &NodeAnnouncementUpdateRequest::ByteSizeLong,
                &NodeAnnouncementUpdateRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(NodeAnnouncementUpdateRequest, _impl_._cached_size_),
            false,
        },
        &NodeAnnouncementUpdateRequest::kDescriptorMethods,
        &descriptor_table_peers_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* NodeAnnouncementUpdateRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 2, 57, 2> NodeAnnouncementUpdateRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::peersrpc::NodeAnnouncementUpdateRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .peersrpc.UpdateAddressAction address_updates = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 1, PROTOBUF_FIELD_OFFSET(NodeAnnouncementUpdateRequest, _impl_.address_updates_)}},
    // repeated .peersrpc.UpdateFeatureAction feature_updates = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(NodeAnnouncementUpdateRequest, _impl_.feature_updates_)}},
    // string color = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(NodeAnnouncementUpdateRequest, _impl_.color_)}},
    // string alias = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(NodeAnnouncementUpdateRequest, _impl_.alias_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .peersrpc.UpdateFeatureAction feature_updates = 1;
    {PROTOBUF_FIELD_OFFSET(NodeAnnouncementUpdateRequest, _impl_.feature_updates_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // string color = 2;
    {PROTOBUF_FIELD_OFFSET(NodeAnnouncementUpdateRequest, _impl_.color_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string alias = 3;
    {PROTOBUF_FIELD_OFFSET(NodeAnnouncementUpdateRequest, _impl_.alias_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .peersrpc.UpdateAddressAction address_updates = 4;
    {PROTOBUF_FIELD_OFFSET(NodeAnnouncementUpdateRequest, _impl_.address_updates_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::peersrpc::UpdateFeatureAction>()},
    {::_pbi::TcParser::GetTable<::peersrpc::UpdateAddressAction>()},
  }}, {{
    "\46\0\5\5\0\0\0\0"
    "peersrpc.NodeAnnouncementUpdateRequest"
    "color"
    "alias"
  }},
};

PROTOBUF_NOINLINE void NodeAnnouncementUpdateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:peersrpc.NodeAnnouncementUpdateRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.feature_updates_.Clear();
  _impl_.address_updates_.Clear();
  _impl_.color_.ClearToEmpty();
  _impl_.alias_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NodeAnnouncementUpdateRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NodeAnnouncementUpdateRequest& this_ = static_cast<const NodeAnnouncementUpdateRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NodeAnnouncementUpdateRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NodeAnnouncementUpdateRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:peersrpc.NodeAnnouncementUpdateRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .peersrpc.UpdateFeatureAction feature_updates = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_feature_updates_size());
               i < n; i++) {
            const auto& repfield = this_._internal_feature_updates().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // string color = 2;
          if (!this_._internal_color().empty()) {
            const std::string& _s = this_._internal_color();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "peersrpc.NodeAnnouncementUpdateRequest.color");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string alias = 3;
          if (!this_._internal_alias().empty()) {
            const std::string& _s = this_._internal_alias();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "peersrpc.NodeAnnouncementUpdateRequest.alias");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // repeated .peersrpc.UpdateAddressAction address_updates = 4;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_address_updates_size());
               i < n; i++) {
            const auto& repfield = this_._internal_address_updates().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    4, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:peersrpc.NodeAnnouncementUpdateRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NodeAnnouncementUpdateRequest::ByteSizeLong(const MessageLite& base) {
          const NodeAnnouncementUpdateRequest& this_ = static_cast<const NodeAnnouncementUpdateRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NodeAnnouncementUpdateRequest::ByteSizeLong() const {
          const NodeAnnouncementUpdateRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:peersrpc.NodeAnnouncementUpdateRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .peersrpc.UpdateFeatureAction feature_updates = 1;
             {
              total_size += 1UL * this_._internal_feature_updates_size();
              for (const auto& msg : this_._internal_feature_updates()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated .peersrpc.UpdateAddressAction address_updates = 4;
             {
              total_size += 1UL * this_._internal_address_updates_size();
              for (const auto& msg : this_._internal_address_updates()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // string color = 2;
            if (!this_._internal_color().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_color());
            }
            // string alias = 3;
            if (!this_._internal_alias().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_alias());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NodeAnnouncementUpdateRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NodeAnnouncementUpdateRequest*>(&to_msg);
  auto& from = static_cast<const NodeAnnouncementUpdateRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:peersrpc.NodeAnnouncementUpdateRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_feature_updates()->MergeFrom(
      from._internal_feature_updates());
  _this->_internal_mutable_address_updates()->MergeFrom(
      from._internal_address_updates());
  if (!from._internal_color().empty()) {
    _this->_internal_set_color(from._internal_color());
  }
  if (!from._internal_alias().empty()) {
    _this->_internal_set_alias(from._internal_alias());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NodeAnnouncementUpdateRequest::CopyFrom(const NodeAnnouncementUpdateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:peersrpc.NodeAnnouncementUpdateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NodeAnnouncementUpdateRequest::InternalSwap(NodeAnnouncementUpdateRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.feature_updates_.InternalSwap(&other->_impl_.feature_updates_);
  _impl_.address_updates_.InternalSwap(&other->_impl_.address_updates_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.color_, &other->_impl_.color_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.alias_, &other->_impl_.alias_, arena);
}

::google::protobuf::Metadata NodeAnnouncementUpdateRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class NodeAnnouncementUpdateResponse::_Internal {
 public:
};

void NodeAnnouncementUpdateResponse::clear_ops() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ops_.Clear();
}
NodeAnnouncementUpdateResponse::NodeAnnouncementUpdateResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:peersrpc.NodeAnnouncementUpdateResponse)
}
inline PROTOBUF_NDEBUG_INLINE NodeAnnouncementUpdateResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::peersrpc::NodeAnnouncementUpdateResponse& from_msg)
      : ops_{visibility, arena, from.ops_},
        _cached_size_{0} {}

NodeAnnouncementUpdateResponse::NodeAnnouncementUpdateResponse(
    ::google::protobuf::Arena* arena,
    const NodeAnnouncementUpdateResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NodeAnnouncementUpdateResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:peersrpc.NodeAnnouncementUpdateResponse)
}
inline PROTOBUF_NDEBUG_INLINE NodeAnnouncementUpdateResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : ops_{visibility, arena},
        _cached_size_{0} {}

inline void NodeAnnouncementUpdateResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
NodeAnnouncementUpdateResponse::~NodeAnnouncementUpdateResponse() {
  // @@protoc_insertion_point(destructor:peersrpc.NodeAnnouncementUpdateResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void NodeAnnouncementUpdateResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    NodeAnnouncementUpdateResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_NodeAnnouncementUpdateResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &NodeAnnouncementUpdateResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<NodeAnnouncementUpdateResponse>(),
            ::google::protobuf::Message::GetNewImpl<NodeAnnouncementUpdateResponse>(),
            ::google::protobuf::Message::GetClearImpl<NodeAnnouncementUpdateResponse>(), &NodeAnnouncementUpdateResponse::ByteSizeLong,
                &NodeAnnouncementUpdateResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(NodeAnnouncementUpdateResponse, _impl_._cached_size_),
            false,
        },
        &NodeAnnouncementUpdateResponse::kDescriptorMethods,
        &descriptor_table_peers_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* NodeAnnouncementUpdateResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> NodeAnnouncementUpdateResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::peersrpc::NodeAnnouncementUpdateResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .lnrpc.Op ops = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(NodeAnnouncementUpdateResponse, _impl_.ops_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .lnrpc.Op ops = 1;
    {PROTOBUF_FIELD_OFFSET(NodeAnnouncementUpdateResponse, _impl_.ops_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::lnrpc::Op>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void NodeAnnouncementUpdateResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:peersrpc.NodeAnnouncementUpdateResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ops_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NodeAnnouncementUpdateResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NodeAnnouncementUpdateResponse& this_ = static_cast<const NodeAnnouncementUpdateResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NodeAnnouncementUpdateResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NodeAnnouncementUpdateResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:peersrpc.NodeAnnouncementUpdateResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .lnrpc.Op ops = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_ops_size());
               i < n; i++) {
            const auto& repfield = this_._internal_ops().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:peersrpc.NodeAnnouncementUpdateResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NodeAnnouncementUpdateResponse::ByteSizeLong(const MessageLite& base) {
          const NodeAnnouncementUpdateResponse& this_ = static_cast<const NodeAnnouncementUpdateResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NodeAnnouncementUpdateResponse::ByteSizeLong() const {
          const NodeAnnouncementUpdateResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:peersrpc.NodeAnnouncementUpdateResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .lnrpc.Op ops = 1;
             {
              total_size += 1UL * this_._internal_ops_size();
              for (const auto& msg : this_._internal_ops()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NodeAnnouncementUpdateResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NodeAnnouncementUpdateResponse*>(&to_msg);
  auto& from = static_cast<const NodeAnnouncementUpdateResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:peersrpc.NodeAnnouncementUpdateResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_ops()->MergeFrom(
      from._internal_ops());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NodeAnnouncementUpdateResponse::CopyFrom(const NodeAnnouncementUpdateResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:peersrpc.NodeAnnouncementUpdateResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NodeAnnouncementUpdateResponse::InternalSwap(NodeAnnouncementUpdateResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.ops_.InternalSwap(&other->_impl_.ops_);
}

::google::protobuf::Metadata NodeAnnouncementUpdateResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace peersrpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_peers_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
