// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: verrpc.proto
// Protobuf C++ Version: 5.28.2

#include "verrpc.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace verrpc {
              template <typename>
PROTOBUF_CONSTEXPR VersionRequest::VersionRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct VersionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VersionRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VersionRequestDefaultTypeInternal() {}
  union {
    VersionRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VersionRequestDefaultTypeInternal _VersionRequest_default_instance_;

inline constexpr Version::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : build_tags_{},
        commit_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        commit_hash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        app_pre_release_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        go_version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        app_major_{0u},
        app_minor_{0u},
        app_patch_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Version::Version(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct VersionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VersionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VersionDefaultTypeInternal() {}
  union {
    Version _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VersionDefaultTypeInternal _Version_default_instance_;
}  // namespace verrpc
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_verrpc_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_verrpc_2eproto = nullptr;
const ::uint32_t
    TableStruct_verrpc_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::verrpc::VersionRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::verrpc::Version, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::verrpc::Version, _impl_.commit_),
        PROTOBUF_FIELD_OFFSET(::verrpc::Version, _impl_.commit_hash_),
        PROTOBUF_FIELD_OFFSET(::verrpc::Version, _impl_.version_),
        PROTOBUF_FIELD_OFFSET(::verrpc::Version, _impl_.app_major_),
        PROTOBUF_FIELD_OFFSET(::verrpc::Version, _impl_.app_minor_),
        PROTOBUF_FIELD_OFFSET(::verrpc::Version, _impl_.app_patch_),
        PROTOBUF_FIELD_OFFSET(::verrpc::Version, _impl_.app_pre_release_),
        PROTOBUF_FIELD_OFFSET(::verrpc::Version, _impl_.build_tags_),
        PROTOBUF_FIELD_OFFSET(::verrpc::Version, _impl_.go_version_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::verrpc::VersionRequest)},
        {8, -1, -1, sizeof(::verrpc::Version)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::verrpc::_VersionRequest_default_instance_._instance,
    &::verrpc::_Version_default_instance_._instance,
};
const char descriptor_table_protodef_verrpc_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014verrpc.proto\022\006verrpc\"\020\n\016VersionRequest"
    "\"\271\001\n\007Version\022\016\n\006commit\030\001 \001(\t\022\023\n\013commit_h"
    "ash\030\002 \001(\t\022\017\n\007version\030\003 \001(\t\022\021\n\tapp_major\030"
    "\004 \001(\r\022\021\n\tapp_minor\030\005 \001(\r\022\021\n\tapp_patch\030\006 "
    "\001(\r\022\027\n\017app_pre_release\030\007 \001(\t\022\022\n\nbuild_ta"
    "gs\030\010 \003(\t\022\022\n\ngo_version\030\t \001(\t2B\n\tVersione"
    "r\0225\n\nGetVersion\022\026.verrpc.VersionRequest\032"
    "\017.verrpc.VersionB.Z,github.com/lightning"
    "network/lnd/lnrpc/verrpcb\006proto3"
};
static ::absl::once_flag descriptor_table_verrpc_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_verrpc_2eproto = {
    false,
    false,
    352,
    descriptor_table_protodef_verrpc_2eproto,
    "verrpc.proto",
    &descriptor_table_verrpc_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_verrpc_2eproto::offsets,
    file_level_enum_descriptors_verrpc_2eproto,
    file_level_service_descriptors_verrpc_2eproto,
};
namespace verrpc {
// ===================================================================

class VersionRequest::_Internal {
 public:
};

VersionRequest::VersionRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:verrpc.VersionRequest)
}
VersionRequest::VersionRequest(
    ::google::protobuf::Arena* arena,
    const VersionRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VersionRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:verrpc.VersionRequest)
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    VersionRequest::_class_data_ = {
        ::google::protobuf::internal::ZeroFieldsBase::ClassData{
            &_VersionRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &VersionRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::internal::ZeroFieldsBase::GetDeleteImpl<VersionRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<VersionRequest>(),
            ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<VersionRequest>(), &VersionRequest::ByteSizeLong,
                &VersionRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(VersionRequest, _impl_._cached_size_),
            false,
        },
        &VersionRequest::kDescriptorMethods,
        &descriptor_table_verrpc_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* VersionRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> VersionRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::verrpc::VersionRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata VersionRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Version::_Internal {
 public:
};

Version::Version(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:verrpc.Version)
}
inline PROTOBUF_NDEBUG_INLINE Version::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::verrpc::Version& from_msg)
      : build_tags_{visibility, arena, from.build_tags_},
        commit_(arena, from.commit_),
        commit_hash_(arena, from.commit_hash_),
        version_(arena, from.version_),
        app_pre_release_(arena, from.app_pre_release_),
        go_version_(arena, from.go_version_),
        _cached_size_{0} {}

Version::Version(
    ::google::protobuf::Arena* arena,
    const Version& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Version* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, app_major_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, app_major_),
           offsetof(Impl_, app_patch_) -
               offsetof(Impl_, app_major_) +
               sizeof(Impl_::app_patch_));

  // @@protoc_insertion_point(copy_constructor:verrpc.Version)
}
inline PROTOBUF_NDEBUG_INLINE Version::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : build_tags_{visibility, arena},
        commit_(arena),
        commit_hash_(arena),
        version_(arena),
        app_pre_release_(arena),
        go_version_(arena),
        _cached_size_{0} {}

inline void Version::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, app_major_),
           0,
           offsetof(Impl_, app_patch_) -
               offsetof(Impl_, app_major_) +
               sizeof(Impl_::app_patch_));
}
Version::~Version() {
  // @@protoc_insertion_point(destructor:verrpc.Version)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Version::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.commit_.Destroy();
  _impl_.commit_hash_.Destroy();
  _impl_.version_.Destroy();
  _impl_.app_pre_release_.Destroy();
  _impl_.go_version_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Version::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Version_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Version::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Version>(),
            ::google::protobuf::Message::GetNewImpl<Version>(),
            ::google::protobuf::Message::GetClearImpl<Version>(), &Version::ByteSizeLong,
                &Version::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Version, _impl_._cached_size_),
            false,
        },
        &Version::kDescriptorMethods,
        &descriptor_table_verrpc_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Version::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 9, 0, 90, 2> Version::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    9, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::verrpc::Version>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string commit = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Version, _impl_.commit_)}},
    // string commit_hash = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Version, _impl_.commit_hash_)}},
    // string version = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Version, _impl_.version_)}},
    // uint32 app_major = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Version, _impl_.app_major_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(Version, _impl_.app_major_)}},
    // uint32 app_minor = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Version, _impl_.app_minor_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(Version, _impl_.app_minor_)}},
    // uint32 app_patch = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Version, _impl_.app_patch_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(Version, _impl_.app_patch_)}},
    // string app_pre_release = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(Version, _impl_.app_pre_release_)}},
    // repeated string build_tags = 8;
    {::_pbi::TcParser::FastUR1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(Version, _impl_.build_tags_)}},
    // string go_version = 9;
    {::_pbi::TcParser::FastUS1,
     {74, 63, 0, PROTOBUF_FIELD_OFFSET(Version, _impl_.go_version_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string commit = 1;
    {PROTOBUF_FIELD_OFFSET(Version, _impl_.commit_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string commit_hash = 2;
    {PROTOBUF_FIELD_OFFSET(Version, _impl_.commit_hash_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string version = 3;
    {PROTOBUF_FIELD_OFFSET(Version, _impl_.version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 app_major = 4;
    {PROTOBUF_FIELD_OFFSET(Version, _impl_.app_major_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 app_minor = 5;
    {PROTOBUF_FIELD_OFFSET(Version, _impl_.app_minor_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 app_patch = 6;
    {PROTOBUF_FIELD_OFFSET(Version, _impl_.app_patch_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string app_pre_release = 7;
    {PROTOBUF_FIELD_OFFSET(Version, _impl_.app_pre_release_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated string build_tags = 8;
    {PROTOBUF_FIELD_OFFSET(Version, _impl_.build_tags_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // string go_version = 9;
    {PROTOBUF_FIELD_OFFSET(Version, _impl_.go_version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\6\13\7\0\0\0\17\12\12\0\0\0\0\0\0"
    "verrpc.Version"
    "commit"
    "commit_hash"
    "version"
    "app_pre_release"
    "build_tags"
    "go_version"
  }},
};

PROTOBUF_NOINLINE void Version::Clear() {
// @@protoc_insertion_point(message_clear_start:verrpc.Version)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.build_tags_.Clear();
  _impl_.commit_.ClearToEmpty();
  _impl_.commit_hash_.ClearToEmpty();
  _impl_.version_.ClearToEmpty();
  _impl_.app_pre_release_.ClearToEmpty();
  _impl_.go_version_.ClearToEmpty();
  ::memset(&_impl_.app_major_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.app_patch_) -
      reinterpret_cast<char*>(&_impl_.app_major_)) + sizeof(_impl_.app_patch_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Version::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Version& this_ = static_cast<const Version&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Version::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Version& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:verrpc.Version)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string commit = 1;
          if (!this_._internal_commit().empty()) {
            const std::string& _s = this_._internal_commit();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "verrpc.Version.commit");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string commit_hash = 2;
          if (!this_._internal_commit_hash().empty()) {
            const std::string& _s = this_._internal_commit_hash();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "verrpc.Version.commit_hash");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string version = 3;
          if (!this_._internal_version().empty()) {
            const std::string& _s = this_._internal_version();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "verrpc.Version.version");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // uint32 app_major = 4;
          if (this_._internal_app_major() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                4, this_._internal_app_major(), target);
          }

          // uint32 app_minor = 5;
          if (this_._internal_app_minor() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                5, this_._internal_app_minor(), target);
          }

          // uint32 app_patch = 6;
          if (this_._internal_app_patch() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                6, this_._internal_app_patch(), target);
          }

          // string app_pre_release = 7;
          if (!this_._internal_app_pre_release().empty()) {
            const std::string& _s = this_._internal_app_pre_release();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "verrpc.Version.app_pre_release");
            target = stream->WriteStringMaybeAliased(7, _s, target);
          }

          // repeated string build_tags = 8;
          for (int i = 0, n = this_._internal_build_tags_size(); i < n; ++i) {
            const auto& s = this_._internal_build_tags().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "verrpc.Version.build_tags");
            target = stream->WriteString(8, s, target);
          }

          // string go_version = 9;
          if (!this_._internal_go_version().empty()) {
            const std::string& _s = this_._internal_go_version();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "verrpc.Version.go_version");
            target = stream->WriteStringMaybeAliased(9, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:verrpc.Version)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Version::ByteSizeLong(const MessageLite& base) {
          const Version& this_ = static_cast<const Version&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Version::ByteSizeLong() const {
          const Version& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:verrpc.Version)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string build_tags = 8;
             {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_build_tags().size());
              for (int i = 0, n = this_._internal_build_tags().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_build_tags().Get(i));
              }
            }
          }
           {
            // string commit = 1;
            if (!this_._internal_commit().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_commit());
            }
            // string commit_hash = 2;
            if (!this_._internal_commit_hash().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_commit_hash());
            }
            // string version = 3;
            if (!this_._internal_version().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_version());
            }
            // string app_pre_release = 7;
            if (!this_._internal_app_pre_release().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_app_pre_release());
            }
            // string go_version = 9;
            if (!this_._internal_go_version().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_go_version());
            }
            // uint32 app_major = 4;
            if (this_._internal_app_major() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_app_major());
            }
            // uint32 app_minor = 5;
            if (this_._internal_app_minor() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_app_minor());
            }
            // uint32 app_patch = 6;
            if (this_._internal_app_patch() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_app_patch());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Version::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Version*>(&to_msg);
  auto& from = static_cast<const Version&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:verrpc.Version)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_build_tags()->MergeFrom(from._internal_build_tags());
  if (!from._internal_commit().empty()) {
    _this->_internal_set_commit(from._internal_commit());
  }
  if (!from._internal_commit_hash().empty()) {
    _this->_internal_set_commit_hash(from._internal_commit_hash());
  }
  if (!from._internal_version().empty()) {
    _this->_internal_set_version(from._internal_version());
  }
  if (!from._internal_app_pre_release().empty()) {
    _this->_internal_set_app_pre_release(from._internal_app_pre_release());
  }
  if (!from._internal_go_version().empty()) {
    _this->_internal_set_go_version(from._internal_go_version());
  }
  if (from._internal_app_major() != 0) {
    _this->_impl_.app_major_ = from._impl_.app_major_;
  }
  if (from._internal_app_minor() != 0) {
    _this->_impl_.app_minor_ = from._impl_.app_minor_;
  }
  if (from._internal_app_patch() != 0) {
    _this->_impl_.app_patch_ = from._impl_.app_patch_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Version::CopyFrom(const Version& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:verrpc.Version)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Version::InternalSwap(Version* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.build_tags_.InternalSwap(&other->_impl_.build_tags_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.commit_, &other->_impl_.commit_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.commit_hash_, &other->_impl_.commit_hash_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.version_, &other->_impl_.version_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.app_pre_release_, &other->_impl_.app_pre_release_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.go_version_, &other->_impl_.go_version_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Version, _impl_.app_patch_)
      + sizeof(Version::_impl_.app_patch_)
      - PROTOBUF_FIELD_OFFSET(Version, _impl_.app_major_)>(
          reinterpret_cast<char*>(&_impl_.app_major_),
          reinterpret_cast<char*>(&other->_impl_.app_major_));
}

::google::protobuf::Metadata Version::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace verrpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_verrpc_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
